### ISSUE TITLE
Crash When Smoothing Alpha?

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#1]
Hammer++ crashed when I tried to use the Paint Alpha tool in the Smoothing mode. it _was_ a custom blend texture, but the raise/lower mode seemed to work fine. it's possible there was nothing to smooth. (I'm not very familiar with the Paint Alpha tool and how it works.)
this was build 8851 of H++, the TF2 version.
[hammerplusplus_20220121_120423_1 mdmp and custom vmt.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7915504/hammerplusplus_20220121_120423_1.mdmp.and.custom.vmt.zip)

**Comment by ficool2** [comment]
Fixed in the next build
