### ISSUE TITLE
[Feature Request] Scale UVs along with geometry from using the Transform function

### ISSUE THREAD

**Issue by WereTech** [ficool2/HammerPlusPlus-Issue-Tracker#10]
I sort of doubt this would be an easy task, given that this could potentially create massive float values that source wouldn't want to handle, but it would be nice to be able to scale something and the textures to also scale with it. Not a necessary thing, but it would help to quickly change geometry that was already made and not have to reconfigure all of the relevant faces. As of right now when you use scale, only the brush sizes are changed and UVs are completely untouched, both the coordinates and size.

**Comment by Iridium-77e** [comment]
Out of curiosity, what difference would this have from the scaling texture lock? I might just not be understanding you correctly. No ill will intended, purely curiosity.

**Comment by WereTech** [comment]
> Out of curiosity, what difference would this have from the scaling texture lock? I might just not be understanding you correctly. No ill will intended, purely curiosity.

Oh, this seems to be my fault entirely, but I never have that texture lock on because I often need to resize brushes to correctly go in-line with their UVs. Never thought to turn that on and expect those results. Like I'm scaling an entire map of mine, I don't expect source stuff to do things correctly ;P

**Comment by WereTech** [comment]
> Does it work for what you needed then? If so, great to hear

Yeah I'm just stupid lol
