### ISSUE TITLE
[Bug] Vertex editing specific power 2 or 3 displacements makes them reset to an unedited state and become power 4

### ISSUE THREAD

**Issue by Coachi1** [ficool2/HammerPlusPlus-Issue-Tracker#103]
Sometimes vertex editing power 2 or 3 displacements makes them become power 4 (random faces, occasionally all of them) and reset the geometry changes made in paint geometry. Can't reproduce it consistently, it happens very randomly.

**Comment by SuperSlimek** [comment]
I can reproduce it every time. Here are the steps:
1. Vertex tool
2. Select all vertices
3. Move any vertex

**Comment by ficool2** [comment]
Fixed in next build
