### ISSUE TITLE
Bug: Opening the Outputs panel crashed Hammer. Could be due to autosaving?

### ISSUE THREAD

**Issue by maxistviews** [ficool2/HammerPlusPlus-Issue-Tracker#104]
- **The crash dump (.mdmp file), if applicable**
-- [hammerplusplus_20220127_192900_1.mdmp.txt](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7954742/hammerplusplus_20220127_192900_1.mdmp.txt)

- **The build number and game you are using Hammer++ for**
-- Mapbase Episodic / Source SDK 2013 SP. Latest Hammer build. 

- **Description of what you were doing when this happened**
-- Had just spawned a few new prefabs and was going to change the outputs on them when Hammer crashed. Perhaps this was due to an autosave, however as it had been a while before the file was autosaved.

**Comment by ficool2** [comment]
Fixed in next update
