### ISSUE TITLE
[Bug] Having custom shaders in a folder loaded by the game can break Hammer++ views

### ISSUE THREAD

**Issue by Moltard** [ficool2/HammerPlusPlus-Issue-Tracker#106]
Someone I know had an issue of the 3d view being totally pink.

He found that the culprit was a folder of shaders/ that he had extracted from other game a while ago.

Here is what it looked like

![image](https://user-images.githubusercontent.com/65123883/151539780-00ac2b78-cbae-44d5-bf93-2d32234922a3.png)

the shader file being here (other shader he had also caused issues)
![image](https://user-images.githubusercontent.com/65123883/151539833-ef22b580-df98-431b-8f56-39c761cfc993.png)

maybe you should do something to not load custom shaders in Hammer++

here is the shader that was causing issues

https://cdn.discordapp.com/attachments/688417128868610110/936582715749302302/shaders.rar

**Comment by Yankumo-Koishi** [comment]
> He found that the culprit was a folder of shaders/ that he had extracted from other game a while ago.

Why did he extracted a shader file from other game?
I don't think this is a custom shader issue, instead, I think it's your friend's issue
I'm using Mapbase (If u dunno what's this, just know it has a lot custom shaders), they all work fine in H++ 3D View
I also have Thexa4's PBR shader, it works fine too in my H++

**Comment by Moltard** [comment]
> > He found that the culprit was a folder of shaders/ that he had extracted from other game a while ago.
> 
> Why did he extracted a shader file from other game? I don't think this is a custom shader issue, instead, I think it's your friend's issue I'm using Mapbase (If u dunno what's this, just know it has a lot custom shaders), they all work fine in H++ 3D View I also have Thexa4's PBR shader, it works fine too in my H++

Well he had extract all the assets from some other games, so it included the materials, models,.. and a shaders folder. and it likely override some default shader of the game (like the lightmappedgeneric one). though, in regular Hammer, it didnt break, so I guess Hammer doesnt load shader but Hammer++ load them

So ye, it was mostly my friend's issue, but still worth reporting in case ficool can figure out what was wrong

**Comment by ficool2** [comment]
Unfortunately I can't fix this because Hammer++ uses its own shaders that need to be loaded, and I can't "toggle" specific shaders off. It would also break any mods that use custom shaders properly.

There is a way to force Hammer++ to not load any custom shaders, by starting it up with -nohammershaders via a shortcut. I don't recommend this though
