### ISSUE TITLE
Hammer++ failed to connect to local steam client

### ISSUE THREAD

**Issue by mattgia49** [ficool2/HammerPlusPlus-Issue-Tracker#108]
This keeps happening when I try to compile. It can compile and I already tried updating steam., and re installing Hammer ++. The error pop up is attached

![Screenshot_1](https://user-images.githubusercontent.com/98360162/151604608-117d1df4-2341-40cf-a62d-128fa47d8d27.png)
.

**Comment by MARK2580** [comment]
This is a bug in the game being launched, not Hammer++ itself.

**Comment by ficool2** [comment]
Your parameters to the game might be incorrect

for CSGO: Make sure you are launching the game with -insecure
for other games: Make sure you have -steam in the parameters
