### ISSUE TITLE
Crashing while using Texture Browser

### ISSUE THREAD

**Issue by Blinkyeah** [ficool2/HammerPlusPlus-Issue-Tracker#109]
Build: 8857

Bug description: Crashing while browsing textures in the texture browser. Happened for quite some times, not really a terrible thing, but at this point I figured I should report it so it could maybe be fixed. Not quite sure if the problem is related to me or it's happening to others too. 

No dump file is created on those crashes, had this problem on build 8856 too. The only thing I can think about is scrolling too fast or having too many textures. 

I can recreate this issue 10/10 if I go ahead and scroll from one end to another.

![x1](https://user-images.githubusercontent.com/98295934/151614298-e5fdb12b-9bda-49b4-bb22-dc21f9343591.png)
![x2](https://user-images.githubusercontent.com/98295934/151614302-d0a236ed-3310-4174-88f7-876fd488074b.png)

**Comment by ficool2** [comment]
Can you open task manager and monitor the memory usage while using the texture browser? It could be simply loading too much stuff in

**Comment by Blinkyeah** [comment]
Is there any way to allocate more memory to hammer++ maybe ? 

![gg](https://user-images.githubusercontent.com/98295934/151662258-b5866a08-659b-437b-92e2-2f7e87191328.png)

**Comment by ficool2** [comment]
Hammer is a 32-bit application, it cannot use more than 2GB of memory. There is nothing I can do about this unfortunately

**Comment by Blinkyeah** [comment]
Okay, I see. I will try to limit the amount of textures.
