### ISSUE TITLE
info_player broken on CSGO

### ISSUE THREAD

**Issue by ByDexterTR** [ficool2/HammerPlusPlus-Issue-Tracker#110]
When I place the player spawn points and render, it doesn't work, but when I do it through the normal hammer, it works without any problems.

**Comment by ficool2** [comment]
I need more information, do you have any FGDs loaded? Do other models render?

**Comment by ByDexterTR** [comment]
I'm using standard FGD, other entities are rendered

**Comment by ficool2** [comment]
There's not much else I can do since this doesn't happen for anybody else. A workaround you can try is modifying the info_player_terrorist and info_player_counterterrorist inside csgo.fgd in Notepad to have the model point to a different one that renders properly
