### ISSUE TITLE
[Feature Request] Flip Models In-Editor

### ISSUE THREAD

**Issue by SethTooQuick** [ficool2/HammerPlusPlus-Issue-Tracker#113]
I'm not sure how useful this would be to other people, but I think if you can scale them, perhaps being able to flip them would be nice too.

This would be useful for things like doors that don't have a left / right variant, or other various things when kitbashing, Just something to think about, not really important for people who can make their own props.

**Comment by MARK2580** [comment]
Many games still don't even support zooming in models, flip is not provided at all, even if this is implemented in Hammer++, it won't work in the game.

**Comment by ficool2** [comment]
This would require modifying models at runtime, something which is out of scope for now. I might consider again in the future when I add an integrated Propper into Hammer++

**Comment by SethTooQuick** [comment]
> MARK2580
It very much so is possible, but not in the way you're describing. As Ficool said, it'd have to be its own new thing. I think it'd the same way Valves autocombine works, where it combines the models and packs it. This would do the same thing. Just flip the model on a chosen axis, and pack it in the BSP on compile.

Like I said, I don't expect you to add this, it's very situational. I just think the option to would be neat if ever someone comes along this point where they'd need to.
