### ISSUE TITLE
[ BUG ]  H++ couldn't figure out what's the Chinese Character

### ISSUE THREAD

**Issue by Yankumo-Koishi** [ficool2/HammerPlusPlus-Issue-Tracker#115]
I don't know if this is an encoding issue, but if your vmf path has any Chinese characters, It'll give you this
![屏幕截图 2022-01-29 131014](https://user-images.githubusercontent.com/61674691/151648359-bcc05dfe-bb1a-4c21-929a-6d335321dad4.png)
And sometimes I couldn't launch my h++ after I got this issue and restart it
I tried to reinstall, but it didn't work
Here's the crash dump
[hammerplusplus_20220129_131250_1_crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7963019/hammerplusplus_20220129_131250_1_crash.zip)

**Comment by MARK2580** [comment]
Maybe you should use only English letters? Personally, my native language is Russian, but knowing the logic of many programs and windows, I prefer to name all folders only in English and not use spaces in paths and names, this saves a lot of nerves with similar problems.

**Comment by Yankumo-Koishi** [comment]
> Maybe you should use only English letters? Personally, my native language is Russian, but knowing the logic of many programs and windows, I prefer to name all folders only in English and not use spaces in paths and names, this saves a lot of nerves with similar problems.

I know this common sense, but the main reason is, I've never got this issue until I updata my h++ to Build 8857. that's why I'm confused and post this issue here

**Comment by ficool2** [comment]
Fixed in next build
