### ISSUE TITLE
[Enhancement] 3D Smooth preview not displaying selections

### ISSUE THREAD

**Issue by DarviL82** [ficool2/HammerPlusPlus-Issue-Tracker#117]
The 3D Smooth preview does not display any selection highlights, making it a bit hard to select surfaces for smoothing groups. (This happens in all hammer versions)

![image](https://user-images.githubusercontent.com/48654552/151666033-178c791b-cfda-4b00-a23b-349f2ffd92cc.png)

Would be nice if it could show a red highlight like how it does in any textured 3D preview.

**Comment by ficool2** [comment]
Added in next build
