### ISSUE TITLE
[Bug] Lighting not updating after vertex manipulation

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#119]
I noticed that the lighting stops being calculated and updated if the brush was modified using the vertex tool, it only helps to move the brush, then the lighting is restored.

https://user-images.githubusercontent.com/11617079/151673812-ba1f9cd4-7030-48a7-82fd-4eb8c23bafb4.mp4

**Comment by ficool2** [comment]
Fixed in next build
