### ISSUE TITLE
[Feature Request] Allow Physics Simulation for non-prop entities

### ISSUE THREAD

**Issue by BerntA** [ficool2/HammerPlusPlus-Issue-Tracker#12]
Build: 8852
Game: Source SDK 2013 MP

Currently I cannot use the physics simulation tool for entities that are not for ex prop_* entities.

If I have these entities:
![image](https://user-images.githubusercontent.com/10424971/150618800-5c26df35-0264-42ae-9c31-c6a518faac11.png)
the simulation will not work for the inventory_item
![image](https://user-images.githubusercontent.com/10424971/150618814-a5a04139-2c2c-4e55-99df-d259a230667d.png)

Could you extend this so that any entity with studiomdl can use the simulation?

**Comment by BerntA** [comment]
My inventory item entity does not have any collision keyvalue, I dunno if this keyvalue is required?
![image](https://user-images.githubusercontent.com/10424971/150618970-ab2a3ff8-f773-4fbc-9250-9384257ee833.png)
would be useful if this function worked regardless, if the model has a valid physics mesh

**Comment by celisej567** [comment]
he is works for non props solids
![image](https://user-images.githubusercontent.com/75926135/150636305-2b90c6e1-8a98-4aba-aa79-6ae407a5e100.png)

**Comment by ficool2** [comment]
Untick `(Entities) Simulate props only`
