### ISSUE TITLE
[Bug] Crash + other issues with Portal 2 assets mounted on SDK 2013

### ISSUE THREAD

**Issue by Chedski** [ficool2/HammerPlusPlus-Issue-Tracker#120]
I'm using the SDK 2013 configuration to make Garry's Mod maps, and for whatever reason Hammer++ does NOT like Portal 2 assets. Build 8857 fixed the crashing issue I was experiencing in the model browser, but P2 assets still consistently show up with missing textures and spam the messages tab with errors. It also seems like there's a bunch of models missing, although that might just be a misconfiguration on my part.
![image](https://user-images.githubusercontent.com/35108470/151675631-54164152-00fb-4ee8-9937-66f408fbdefc.png)
![image](https://user-images.githubusercontent.com/35108470/151675505-c086d23d-cf6b-4f43-b727-e7253b500add.png)

**Comment by Chedski** [comment]
After a check with VTFedit, a good chunk of these files seem to have a version of 7.5. Is there a way to get these working? (eg. copying something, probably a dll, from gmod)

**Comment by Chedski** [comment]
The issue with models not being present was just because I left "door" in the filter box, oops
It's crashing again :/

**Comment by Chedski** [comment]
Looks like the missing models was just a filter of "door", oops. Removing the filter causes the model browser to start crashing h++ again.
![image](https://user-images.githubusercontent.com/35108470/151677022-bd2c9c3c-b1f0-4d2d-8dcb-3729ca3a7e86.png)

.mdmp file:
[hammerplusplus_20220129_154044_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7964692/hammerplusplus_20220129_154044_1.zip)

**Comment by Chedski** [comment]
Specific models that cause crashes:
- models/anim_wp/arm_interior_192/laserplatform_rubble

**Comment by ficool2** [comment]
L4D2, Portal 2 and CSGO models are impossible to support under the SDK2013 version. You have the choice of not using the assets, converting the assets to old versions by using VTFVer and Crowbar, or using the CSGO version of Hammer++ with the game configuration pointed to Portal 2.
