### ISSUE TITLE
[bug] moving displacement brushes with the vertex tool breaks them

### ISSUE THREAD

**Issue by shakez0901** [ficool2/HammerPlusPlus-Issue-Tracker#122]
This happens on build 8857
If you move vertices of a displacement around using the vertex tool, it basically resets the displacement (geometry and other changes like painted alpha or attributes are back to how they were when creating the displacement) and changes its power to 4

**Comment by Yashirmare** [comment]
#103

**Comment by ficool2** [comment]
Fixed in build 8858
