### ISSUE TITLE
Turning power two displacements into power three causes a memory error.

### ISSUE THREAD

**Issue by WillAlfred** [ficool2/HammerPlusPlus-Issue-Tracker#123]
These screenshots are the aftermath of said issue. I've managed to reproduce said problem thrice, only having screenshots of the 2nd and 3rd happening.
![image](https://user-images.githubusercontent.com/33255998/151724585-1b5f8c9e-82db-47cf-b5c1-2231ffccb040.png)
![image](https://user-images.githubusercontent.com/33255998/151724592-8a32cd6b-c845-411f-82eb-2044ca62f938.png)

Heres how to reproduce this;
1. Make multiple power two displacements, and add information to it ( Edit it ), 
2.  Then, Select all displacements and apply power three to them.

**Comment by Jboby1** [comment]
I believe this happens anytime you try to increase a displacement's power level. I just had this happen when I turned a power 3 displacement into a power 4.

**Comment by ficool2** [comment]
Fixed in next update
