### ISSUE TITLE
[Bug, 8858, CS:GO] Overlay and Sprite model missing with custom fgd use

### ISSUE THREAD

**Issue by totesmaggots** [ficool2/HammerPlusPlus-Issue-Tracker#130]
I'm using an edited version of the portal 2 fgd from Teamspen's Hammer Addons in my setup for Portal 2 and I can no longer get sprites or overlays to show up after the latest update. No directory was changed but I did try copying the hammer addons' content folder into csgo root folder directly but it had no effect. 

[portal2fgd - Copy.txt](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7972528/portal2.-.Copy.txt)

**Comment by ficool2** [comment]
Does it behave the same in stock Hammer when using the exact same FGD setup?

**Comment by totesmaggots** [comment]
Nope. I just set up stock csgo hammer with the same configuration I have for Hammer++. Overlays, sprites, and all of teamspen's postcompiler entities load correctly.
