### ISSUE TITLE
[Feature Request] Custom Tool Materials

### ISSUE THREAD

**Issue by SpyShadow117** [ficool2/HammerPlusPlus-Issue-Tracker#133]
I am sharing my custom tool materials. I created these years ago to make it easier on my eyes. Your Team is Welcome to include them in the project for everyone. I installed them in the "bin\hammerplusplus\materials" folder. You could put in the readme, if people wish to disable them, simply delete the "tool" folder.

[tools_materials.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7973778/tools_materials.zip)
.

**Comment by ficool2** [comment]
Thirdparty addons are out of scope for Hammer++
