### ISSUE TITLE
[Bug TF2 8858] Crash on Startup after Update

### ISSUE THREAD

**Issue by meatloaf97** [ficool2/HammerPlusPlus-Issue-Tracker#135]
Consistent crash on startup after updating from build 8857. The first crash came after selecting the "About" option from Help. After that, crashes immediately occur. First file is latest crash from this build, second file is from the first crash involving the About tab
(Can't figure out how to add a label, please do it for me)
[hammerplusplus_20220131_171407_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7974618/hammerplusplus_20220131_171407_1.zip)
[hammerplusplus_20220131_170527_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7974638/hammerplusplus_20220131_170527_1.zip)

**Comment by ficool2** [comment]
The crash dumps tell me its crashing inside Windows in a DLL named "K_FPS32.dll". This appears to be the Razer Cortex software, try disabling whatever it's doing

**Comment by meatloaf97** [comment]
Thanks, worked out
