### ISSUE TITLE
[Bug] Disable shadows (solved)

### ISSUE THREAD

**Issue by DrinklyDram** [ficool2/HammerPlusPlus-Issue-Tracker#140]
"Disable Shadows" parameters are duplicated in any version of hammer or ++ one
![image](https://user-images.githubusercontent.com/40040054/151962461-cabe499c-e8c4-48af-9aac-1101f6e3e126.png)

**Comment by MARK2580** [comment]
I don't have that problem (and never have)
![UMEDIhZ7hn](https://user-images.githubusercontent.com/11617079/151964591-cc3429f6-0726-474c-bb26-8f0ebc1e82f9.png)

**Comment by Moltard** [comment]
it might be due to a fgd  you loaded

problem of duplicate could happen with output on the base Hammer with the way some fgd were made
