### ISSUE TITLE
[Bug] Selection by holding LMB

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#146]
In Hammer++ it is not possible to select objects one by one by holding down the mouse. To be more precise, the objects begin to be selected one by one "by layers".
This functionality is in the standard Hammer.

![hammer_7wyivOLFhQ](https://user-images.githubusercontent.com/11617079/152215922-4eee962a-7a54-4388-b88d-3a636ce4d98a.gif)

**Comment by ficool2** [comment]
This was replaced in Hammer++ by middle click in 3D view (if you are using Gmod controls, its Shift + middle click) or Pg Up/Pg Down keys, because holding LMB was dumb

**Comment by MARK2580** [comment]
> 

Oh, thanks for the tip ) To be honest, I just found out today that this can be done in the standard Hammer, I was asked to make this post.
