### ISSUE TITLE
[Feature Request] Hot reload gameinfo.txt

### ISSUE THREAD

**Issue by JamesT-W** [ficool2/HammerPlusPlus-Issue-Tracker#15]
Hot reload gameinfo.txt while hammer++ is open, rather than requiring a restart.
Would it be possible for this to be done by only reloading things that are in an added/removed SearchPath to reduce loading time?
Currently you would have to completely restart hammer++ to see gameinfo changes applied, therefore wasting a lot of time on big maps.

**Comment by ficool2** [comment]
This would require a complete re-structure of how Hammer handles assets and it might also break the engine itself as it doesn't expect such behavior
