### ISSUE TITLE
[BUG] info_player_terrorist & info_player_counterterrorist don't get placed floating above brushes

### ISSUE THREAD

**Issue by WunkaFaceball** [ficool2/HammerPlusPlus-Issue-Tracker#150]
When placing info_player_terrorist and info_player_counterterrorist, they don't get placed slightly above the brush, making them invalid for some reason. Default CSGO hammer does this. This is an issue because when CT and T spawns aren't floating slightly, that spawn point isn't usable. (sorry idk how else to describe it
![info_player_counterterrorist](https://user-images.githubusercontent.com/98230044/152406014-866e5984-5131-47f4-a772-922c62d6bb7a.png)
)

**Comment by ficool2** [comment]
Fixed in next update
