### ISSUE TITLE
[Feature Request] Lightmap / Static Prop Lighting Editor

### ISSUE THREAD

**Issue by Luctaris** [ficool2/HammerPlusPlus-Issue-Tracker#151]
Hello,

Since lighting is now able to be calculated and displayed in Hammer++, it would be nice to have the ability to individually edit brush face light maps and static prop vertex lighting values in the new lighting preview. This feature would essentially allow the mapper to override VRAD lighting calculations with custom values.

There are a few standalone tools that have been released over the years (https://github.com/Sergey-KoRJiK/SourceEngineBSPditor, https://github.com/Enderlux/sourcelightmap) that already accomplish this on compiled BSP files.

Thanks for your time on this project and consideration.

**Comment by MARK2580** [comment]
I doubt very much that this can be done without custom compilers, hammer++ just shows approximate lighting, which nevertheless differs from the final version, especially if it is, for example, csgo where there are lightmaps on models and cascading shadows.

**Comment by ficool2** [comment]
Out of scope, this would require compiler changes
