### ISSUE TITLE
[Feature Request] Preview the limits

### ISSUE THREAD

**Issue by 1mBubble** [ficool2/HammerPlusPlus-Issue-Tracker#153]
Is it possible to make preview the limits without compiling the map?

**Comment by DrinklyDram** [comment]
What limits are you talking about?

**Comment by 1mBubble** [comment]
total number of areaportals, unique vertices, etc?

**Comment by 1mBubble** [comment]
It would be cool if, for example, such data would be displayed before compilation. At least some of them.![5Hv2Yus_d.png](https://user-images.githubusercontent.com/34455151/152609062-2671afa4-20b2-4e3b-808c-8b27dc8e2267.png)

**Comment by DarviL82** [comment]
Most of this information can only be known after the map is compiled, such as the leaves limit.
Maybe some like the brush and surface count would be possible, but why? It doesn't take too much to make a fast compile and check it.

**Comment by 1mBubble** [comment]
In games like Garry's mod take over 20-30 minutes to compile maps in fast mode due to their size and shitty optimization. I'm not talking about displaying all limits, at least part of them. I think to some extent it is possible.

**Comment by ficool2** [comment]
Out of scope, you can just run the compilers if you want to see limits anyway
