### ISSUE TITLE
[Bug] Incorrect lighting simulation at joints

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#154]
Quite often I notice that the lighting at the joints / corners is calculated very strangely, most often the light seems to shine through them. Here are screenshots from the game and hammer++ for comparison
![bug1](https://user-images.githubusercontent.com/11617079/152582399-319c29aa-90f0-4e4e-95f6-462abf9efa44.jpg)
![bug2](https://user-images.githubusercontent.com/11617079/152582414-1559519d-773f-4dac-a8f5-485cfc796f5d.jpg)

**Comment by DrinklyDram** [comment]
This feature named "Lighting PREVIEW". The idea is not to please the eye. Do you want to wait for a long time just to see your lighting?

**Comment by MARK2580** [comment]
> This feature named "Lighting PREVIEW". The idea is not to please the eye. Do you want to wait for a long time just to see your lighting?

The screenshot with the window shows too much difference in lighting, this is definitely not acceptable. I tried setting the lighting preview to large values, I even tried setting the lightmap to 2, but the lighting was still not correct and there were bright edges.
Hammer++ displays the future lighting quite accurately, but for some reason the corners and joints of the walls are very bad for him.

**Comment by ficool2** [comment]
This can't be fixed because VRAD uses the chopped map generated by VBSP which fixes this kind of "bleed". You can improve it by changing your geometry to not intersect past each other, and you can also try enabling "Light bleed hack" setting.

**Comment by MARK2580** [comment]
> This can't be fixed because VRAD uses the chopped map generated by VBSP which fixes this kind of "bleed". You can improve it by changing your geometry to not intersect past each other, and you can also try enabling "Light bleed hack" setting.

I always use the blend hack, too bad it can't be fixed. By the way, about changing the geometry, I just kept changing my map and now the lighting is normal in the same corner.
![saa0wNIONc](https://user-images.githubusercontent.com/11617079/152787856-ee6b02f7-d940-4b60-809a-be39615c3a02.jpg)
