### ISSUE TITLE
[Bug] CSGO #8858, Crash when changing displacement power from 2 to 3

### ISSUE THREAD

**Issue by JamesT-W** [ficool2/HammerPlusPlus-Issue-Tracker#157]
Here's the mdmp
[mdmp.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8007336/mdmp.zip)

**Comment by DrinklyDram** [comment]
This issue report already exists.
https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/123

**Comment by JamesT-W** [comment]
Wasn't sure if this was in build 8858 though as it was 6 days ago and 8858 released on 30th Jan

**Comment by DrinklyDram** [comment]
So it wasn't.

**Comment by ficool2** [comment]
Fixed in the next build
