### ISSUE TITLE
[Bug, 8858, TF2] Crash When Painting Alpha

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#160]
this time, I was just messing with normal `dev/dev_blendmeasure`. more specifically, I was trying to paint alpha with the 3rd "raise to" brush, but as soon as I clicked on the displacement, H++ crashed. brushes 1 and 2 worked just fine.
[raise alpha brush 3 crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8008453/raise.alpha.brush.3.crash.zip)

**Comment by Kestrelguy** [comment]
same thing happens with the "raise to" large dot brush.
[raise alpha brush 6 crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8008470/raise.alpha.brush.6.crash.zip)

**Comment by Kestrelguy** [comment]
also seems to happen with brush 2, but only when I try to use it on an edge. I didn't check if this was also with the other brushes, and I can't be bothered to.
[raise alpha brush 2 crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8008484/raise.alpha.brush.2.crash.zip)

**Comment by Kestrelguy** [comment]
now it happened with brush 1. which I'd been using for a while with no problem.
[raise alpha brush 1 crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8008496/raise.alpha.brush.1.crash.zip)

**Comment by Kestrelguy** [comment]
aand now it just happened with the small dot brush. possibly worth noting that I was painting an edge vertex.
[raise alpha brush 7.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/8008506/raise.alpha.brush.7.zip)

**Comment by ficool2** [comment]
Fixed in next update
