### ISSUE TITLE
[Bug, 8858, TF2] Lighting Preview Turns Misplaced Lights into Disco Balls

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#163]
if a light is inside a solid brush when you run the lighting preview, it'll cast light in the appropriate direction, but spottily.
![image](https://user-images.githubusercontent.com/97305860/152658916-58720086-cf68-45ae-a113-852659cede40.png)

**Comment by ficool2** [comment]
Can't fix as it would make lighting preview slower, just move your light down 1 unit
