### ISSUE TITLE
[BUG, 8858, SP2013/EP2] Issues with Entities within Instances

### ISSUE THREAD

**Issue by nessinby** [ficool2/HammerPlusPlus-Issue-Tracker#164]
In Hammer++, using an (a)instance nested inside of a secondary (b)instance causes the nested (a)instance to be rotated to the world rather than the (b)instance. Ie, if a (a)Instance is pointing [->]east in the (b)instance, but the (b)instance is rotated -90 degrees to look [<-]west in the world, then (a)instance inside of (b)instance is still pointing [->]east in-game, instead of the pointing in the expected [^]north direction.

![image](https://user-images.githubusercontent.com/4097846/152667022-d9a25a83-7773-43df-a2bd-6b420eae2562.png)
Visualization, the Big Arrow is pointing [^]North, smaller arrows are pointing in the direction of the instance it's next to or inside of. The buildings are (b)instances, while the walls are (a)instances. The (b)instance building to the left is pointing [->]East, while the (a)instance door is pointing [->]East inside of the (b)instance, so it works fine. But even though the right (b)instance building is pointing [^]north, the (a)instance door for that one is still pointing [->]east.

As well, I'm having general issues with entities, brushes and otherwise, inside of instances. Props, func_breakable, func_triggers, etc all lose their location. Instead, they end up offset around the world origin and rotation, rather than the instance origin and rotation.
![image](https://user-images.githubusercontent.com/4097846/152667215-d22a23e4-fe27-4049-bb5a-336ca4a591ed.png)
![image](https://user-images.githubusercontent.com/4097846/152667665-7b1e8132-e678-4a9a-8287-7bbb66e2b2a8.png)

Images were captured using Garry's Mod, however the Compilers are pointed at the SP2013 SDK compilers, and the issues still occur inside the Ep2 game. 
![image](https://user-images.githubusercontent.com/4097846/152667288-59783747-f9f3-4ebe-90e4-a7db1845bc98.png)

This occurred on builds 8849->8858, have not tested builds earlier than that.

**Comment by ficool2** [comment]
This happens due to SDK 2013 SP missing the GameData entry in the gameinfo.txt, you need to add that in (see Garry's Mod gameinfo.txt and then copy the GameData entry into SDK 2013 SP's gameinfo.txt, or whichever game you are mounting it under)

**Comment by nessinby** [comment]
Hello! I'm sorry, but I've attempted your solution and it didn't work. While the GameInfo.txt that I'm using (SDK2013/Ep2) did lack the appropriate GameData field, I've since filled it with the appropriate solution, to no help. I am sure it is the right gameinfo, as it's the same one I modified to add in a custom folder mount, and the one referenced inside the Hammer Settings for Ep2. I've tried pointing the Gamedata reference at a few different .fgd's, to no avail. The halflife2.fgd, base.fgd, hammerplusplus/hammerplusplus_fgd.fgd, copying the garrysmod.fgd into the 2013sdk /bin folder and trying that, clearing out the linked .fgd's in hammer and ensuring only the essentials are linked (H++ & Gmod, H++ & HL2, H++ + HL2 + Gmod,).fgd . Non of the attempted solutions worked, or even had any change to the result of the build. 

I'm not sure what I'm doing wrong.

**Comment by nessinby** [comment]
Ok, update. I managed to somewhat fix it. With the GameData inserted into the GameInfo, I found I could use the Gmod VBSP compiler, which worked. While there are other problems now, due to VBSP lacking Ep2 Content, I think I can figure those out.
