### ISSUE TITLE
[BUG] Entity Report tool duplicated every prop on map.

### ISSUE THREAD

**Issue by Danoncho** [ficool2/HammerPlusPlus-Issue-Tracker#166]
So, I tried to change some parameters of props through Map -> Entity Report tool, and it just duplicated every prop on my map for no reason. No matters what type prop is, doors, rocks, trees, lamps, static, dynamic, everything duplicated.

**Comment by DrinklyDram** [comment]
I don't have this bug. Maybe you accidentally pressed Ctrl + D while your props where selected?

**Comment by Danoncho** [comment]
Maybe... That's strange cause I didn't notice when exactly this happened, I was using Entity Report at that moment. At least I can revert to previous iteration of the map. Probably this was my mistake.
