### ISSUE TITLE
[Feature Request] Reset the sequence of properties in columns

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#168]
I would like hammer++ to have one small useful function. For example, I think any mapper already purely visually remembers where the name field is located in the property column, where the model is, etc. But when you sort columns by name or parameter, there is no way to return the standard sorting, and the only solution is to completely restart the editor. Those. something similar to resetting a property to a default value, a thread right-clicking on a column header, for example.

https://user-images.githubusercontent.com/11617079/152679042-d4c293cc-e0d7-46d3-bed9-708580e01841.mp4

**Comment by DrinklyDram** [comment]
Happened to me many times

**Comment by Qdude21** [comment]
This is fixable, in default Hammer and ++. Just click SmartEdit and then click SmartEdit again to go back. The orders of the stuff will be fixed.

**Comment by DrinklyDram** [comment]
oh

**Comment by DrinklyDram** [comment]
@MARK2580 add " (solved)" to the title

**Comment by MARK2580** [comment]
> This is fixable, in default Hammer and ++. Just click SmartEdit once and then again to go back. The orders of the properties will be fixed.

😮 almost 13 years later, I'm learning something new about hammer again
