### ISSUE TITLE
Exception Code: 0xc0000005

### ISSUE THREAD

**Issue by Astrroo** [ficool2/HammerPlusPlus-Issue-Tracker#17]
EXCEPTION_ACCESS_VIOLATION

This error had occurred during the Postload Processing phase of loading my .vmf. It's very large, unsure if that's an issue.

**Comment by Astrroo** [comment]
Build #: 8853 using it for SDK2013

https://drive.google.com/file/d/1G4Ji5hOhlkf_PIYNQ1xCXItbXnigEoKy/view?usp=sharing mdmp file

**Comment by MARK2580** [comment]
I got this error when I was just trying to select a light source color.
https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/18

**Comment by ficool2** [comment]
> Build #: 8853 using it for SDK2013
> 
> https://drive.google.com/file/d/1G4Ji5hOhlkf_PIYNQ1xCXItbXnigEoKy/view?usp=sharing mdmp file

Are you sure you are using Build 8853? The mdmp tells me you are using Build 8852, and this specific crash was fixed in Build 8853

**Comment by BerntA** [comment]
I got this issue out of nowhere when editing a func_button
![image](https://user-images.githubusercontent.com/10424971/150641705-c9e5106f-7c9e-44d8-965d-51fd351f0735.png)
dump:
[hammerplusplus_20220122_150704_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7918495/hammerplusplus_20220122_150704_1.zip)

**Comment by Astrroo** [comment]
> > Build #: 8853 using it for SDK2013
> > https://drive.google.com/file/d/1G4Ji5hOhlkf_PIYNQ1xCXItbXnigEoKy/view?usp=sharing mdmp file
> 
> Are you sure you are using Build 8853? The mdmp tells me you are using Build 8852, and this specific crash was fixed in Build 8853

Yup, the .zip that contains the hammer++ files I used says 8853. As long with the error as well.

**Comment by ficool2** [comment]
Fixed in build 8855

**Comment by Astrroo** [comment]
mdmp: https://drive.google.com/file/d/1UlHa6ITiMOsmSM6cZRXmLFITjaLd_TWo/view?usp=sharing

Might as well give the VMF. Same issue.

https://drive.google.com/file/d/11y3ml7DyF_fG-LdvxjQc0mwEY3roLTQR/view?usp=sharing

**Comment by ficool2** [comment]
It looks like it keeps crashing because the entities are not defined correctly, check your game configuration to see if you have the correct FGDs mounted (it is crashing while trying to load the npc_strider)

**Comment by Astrroo** [comment]
That seemed to be the issue. Had both SDK2013 and GMOD .base fgds added. Just removed SDK2013, map loads now, thank you!
