### ISSUE TITLE
[Bug, CS:GO] env_steam is rotated incorrectly

### ISSUE THREAD

**Issue by DrinklyDram** [ficool2/HammerPlusPlus-Issue-Tracker#170]
env_steam in any Hammer has 90 degrees difference with in-game steam. Model "models/editor/spot_cone.mdl" needs to be rotated 90 degrees clockwise and then replaced in fgd.
![image](https://user-images.githubusercontent.com/40040054/152693761-27670c15-14e4-4f03-a9b2-7fa64bdc0148.png)

**Comment by ficool2** [comment]
This is an FGD issue rather than a Hammer issue, and those are out of scope to fix here

**Comment by DarviL82** [comment]
Just fyi @DrinklyDram, HammerAddons' FGD fixed this in case you want to take a look.
