### ISSUE TITLE
Whenever "Raise to" is used for displacement alpha editing on a sewed edge

### ISSUE THREAD

**Issue by Squaggies** [ficool2/HammerPlusPlus-Issue-Tracker#171]
Build: 8858 in TF2
cant upload the minidump file directly to github so here it is on drive: [https://drive.google.com/file/d/1mbhw0_a82BdX9aq-ESYSiQrEBinzDJdD/view?usp=sharing](url)
Very consistent for me, working on detailing my map's water and using these seafoam textures: [https://tf2maps.net/downloads/canaveral-water.10980/update?update=31901](url) any time i try to edit the alpha of the sewed edge with the raise to setting it crashes instantly. I would assume it might have something to do with textures which already have alpha built into them making something weird happen. If you'd like the vmf file ping me on the tf2maps discord and i'll dm you the map vmf

the smooth option also crashes too

**Comment by DrinklyDram** [comment]
Is it similar or equal to https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/160 ?

**Comment by Squaggies** [comment]
seems like the same issue, there are some things that work fine though, like sewing 2 edges that are next to eachother but using other options on the edge seems to crash it

**Comment by ficool2** [comment]
Fixed in next update
