### ISSUE TITLE
[Bug, 8858] Crash when changing power of a displacement. 

### ISSUE THREAD

**Issue by Tuckatk** [ficool2/HammerPlusPlus-Issue-Tracker#173]
When I tried to change a already existing displacement that was the power of 2 and try to apply it to the power of 3, Hammer++ crashes as seen in the screenshot provided. When reducing a power of 3 to 2 though works just fine.  I am currently using the SDK 2013 Multiplayer version if that also helps to isolate the issue.

![DisplacementIssue](https://user-images.githubusercontent.com/16376222/152700181-f05a1a72-5506-4736-a1f4-fb19da619e97.PNG)

**Comment by DrinklyDram** [comment]
This issue report is equal to https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/123 and https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/157
