### ISSUE TITLE
[Feature Request] Preview move linear, track train, etc.

### ISSUE THREAD

**Issue by BerntA** [ficool2/HammerPlusPlus-Issue-Tracker#174]
It would be nice to have realtime previews (movement + angles) of these func entities like func_tracktrain, func_movelinear, etc to save time.

**Comment by ficool2** [comment]
I created something like this a long time ago but it was too much of a burden to maintain, as each movement entity behaves differently, so unfortunately I won't add this


https://user-images.githubusercontent.com/34815548/152884272-e8856665-d280-4a73-b626-7ac571fc1709.mp4
