### ISSUE TITLE
BUG | Crash when I use smooth and non-spatial brush with displacment tool.

### ISSUE THREAD

**Issue by Avocadocs** [ficool2/HammerPlusPlus-Issue-Tracker#176]
**Build:** 8858
**Game:** CS:GO

I retryed 3 times and still happening, hammer++ just crashes. It happens when I use smooth and non-spatial brush with displacment tool. 

![image](https://user-images.githubusercontent.com/97396830/152961399-0130f0bf-4151-4b11-9d1e-aee3f72ad2ae.png)

Crash file (I can't put it on github ^^): https://www.mediafire.com/file/w35ogzacebb7sny/hammerplusplus_20220208_104426_1_x27CBF478.mdmp/file

**Comment by ficool2** [comment]
Fixed in next update
