### ISSUE TITLE
EXECPTION_ACCESS_VIOLATION 0x0000005 [8853]

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#18]
I just tried again to select a color for the light source and got this error.

![IR9rtFUQqF](https://user-images.githubusercontent.com/11617079/150627721-6c7caed0-04a1-48b8-87bb-c048791eacc4.png)

UPD: I think I understand, this happens if you edit several merged "lights" at once
[reports.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7918009/reports.zip)

**Comment by ficool2** [comment]
Should be fixed next update
