### ISSUE TITLE
[BUG] #8859 AutoSave Issue (0x20)

### ISSUE THREAD

**Issue by Rushaway** [ficool2/HammerPlusPlus-Issue-Tracker#180]
When autosave is triggered you have an error message.
Error : (0x20)
Space left on my Disk 250Go.
Path and file correctly exist in autosave folder.
![unknown](https://user-images.githubusercontent.com/11679883/153186444-0d023622-4856-4937-8afb-fe2e785db5ca.png)

**Comment by MARK2580** [comment]
Today I downloaded version 8859 and got the same error, although I have 555gb free on the disk.

![JOQXKbRoKn](https://user-images.githubusercontent.com/11617079/153201321-eac737d7-db6a-438e-bca2-a809c3a0df67.png)
![28fZyFAxV0](https://user-images.githubusercontent.com/11617079/153201780-2c6ba87f-15d0-4b6c-9e66-7d5e567bd78a.png)

**Comment by DrinklyDram** [comment]
idk maybe it's somehow connected with https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/149 cause i said this bug could be connected with autosaves and either ficool has fixed that bug but broken autosaves or he decided to disable autosaves to check will this bug (#149) appear after that
