### ISSUE TITLE
request

### ISSUE THREAD

**Issue by yagos24** [ficool2/HammerPlusPlus-Issue-Tracker#195]
will there ever be hammer++ for gmod? because when I searched on yt of the tutorials the tutorials did not work

**Comment by MARK2580** [comment]
More than once it has been said that there will be no Gmod. You can work fine under SDK2013MP and compile via gmod.

**Comment by ficool2** [comment]
Unless its commissioned, there will be no native Garry's Mod support

**Comment by WolfeStrider** [comment]
> Unless its commissioned, there will be no native Garry's Mod support

How do I commission you then? I can't seem to get a hold of you on Discord, Steam, or Ko-fi
