### ISSUE TITLE
Not Working Sun Samples option in Light Preview.

### ISSUE THREAD

**Issue by celisej567** [ficool2/HammerPlusPlus-Issue-Tracker#20]
When i change sun samples from 6 to 1 or 1000 its the same quality.
Sun Samples = 6
![image](https://user-images.githubusercontent.com/75926135/150632168-2889254a-1be2-44c4-8e84-4b2ceec0e619.png)
Sun Samples = 1
![image](https://user-images.githubusercontent.com/75926135/150632140-f6a62d22-5831-434c-ba6f-0b8748853999.png)
Sun Samples = 1000
![image](https://user-images.githubusercontent.com/75926135/150632107-228580b5-df99-4b0f-b66b-1f009169d493.png)

**Comment by ficool2** [comment]
Sun samples will only have an effect if the "SunSpreadAngle" property in light_environment is more than 0, otherwise its always 1 sample
