### ISSUE TITLE
Lighting preview only uses one sun sample, but only on one specific map.

### ISSUE THREAD

**Issue by WormSlayer** [ficool2/HammerPlusPlus-Issue-Tracker#208]
Not sure why, but this one map of mine will only ever preview the lighting with a single sun sample, no matter what number is in the Sun Samples box. I dont think its just ignoring SunSpreadAngle, because of how quickly it bakes the lighting.

**Comment by ficool2** [comment]
This happens if you have multiple light_environments in the map, you need to ensure only 1 is visible
