### ISSUE TITLE
[Bug, 8860, TF2] Saveless Crash for No Apparent Reason?

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#221]
I wasn't doing anything extraordinary. I had 16 `info_player_teamspawn`s selected? maybe that was it? took a moment, though. and then it crashed, with no autosave or crash dump.
I didn't bother taking a screenshot, 'cuz it was the same message as #206. 
![image](https://user-images.githubusercontent.com/97305860/153954017-3ca1ffd7-b7d8-42ea-b2b2-8d70c2a748e6.png)

**Comment by ficool2** [comment]
Unless this is consistent, I can't do anything about this
