### ISSUE TITLE
[Bug, 8860, SDK2013MP] Entities exchange their classnames with other entities randomly during access via I/O

### ISSUE THREAD

**Issue by BerntA** [ficool2/HammerPlusPlus-Issue-Tracker#224]
A strange bug keeps happening to me from time to time when editing entities input/outputs/properties, whilst I do random edits an entity might suddenly go from let's say logic_relay to trigger_once, or vice versa? 

![image](https://user-images.githubusercontent.com/10424971/154769715-6ae7ed11-b4b3-4a7e-b6ec-c581d2fb66b7.png)

happens a lot when I have to change a lot of I/O stuff, especially when I use the Input -> Mark or Output -> Mark it might suddenly exchange the target entity with the original entity you switched from

go @ trigger_once which has output to trigger_relay, go back again via input, etc etc = suddenly relay ent gets fucked..

**Comment by GXP10** [comment]
didn't know there is someone report this issue first but mine have a video evidence when it happens
#235

**Comment by ficool2** [comment]
Do you have any consistent method of reproducing this? I can't get this to happen

**Comment by GXP10** [comment]
> Do you have any consistent method of reproducing this? I can't get this to happen

I think there's a factor that causing that like lag, alot of I/O stuff
I already sent you a vmf in discord so maybe you can try it out

**Comment by BerntA** [comment]
Yeah, its pretty hard to reproduce this issue, when you have a fairly large map, and you hide + unhide stuff while doing random I/O changes on entities it might suddenly happen, especially when there is a lot of lag due to entity I/O changes.. :| can be unbearable at times

**Comment by WormSlayer** [comment]
I am also unable to figure out what causes this bug, but I've been bitten by it a couple of times now. If it would help with the diagnosis, I can provide the maps it happened to.

**Comment by ficool2** [comment]
Fixed in Build 8861
