### ISSUE TITLE
Bug: 2013sp_build8860 - 3d skybox preview doesn't work at all

### ISSUE THREAD

**Issue by luxeleios** [ficool2/HammerPlusPlus-Issue-Tracker#225]
Not much to say besides the title. 2d sky preview and every other preview works as intended but the 3d sky one doesn't, no matter the map and sky camera pos.

**Comment by DrinklyDram** [comment]
hey, you should turn the whole 3d skybox including sky_camera into an instance

**Comment by luxeleios** [comment]
Okay, I'll try it, thanks, but I dont think Ive seen it mentioned anywhere. Also it means no lighting preview unfortunately :(

**Comment by MARK2580** [comment]
> Not much to say besides the title. 2d sky preview and every other preview works as intended but the 3d sky one doesn't, no matter the map and sky camera pos.

https://www.youtube.com/watch?v=LL7iFGcINkA

**Comment by luxeleios** [comment]
Yeah it works when it's an instance, we've settled that.
