### ISSUE TITLE
prop_dynamic missing vscript properties

### ISSUE THREAD

**Issue by nuclearsilo583** [ficool2/HammerPlusPlus-Issue-Tracker#226]
Newest update cause the existed prop_dynamic missing the vscript properties.
![image](https://user-images.githubusercontent.com/58926275/154801362-db130c44-30db-4302-a5ee-d236f0393a7c.png)
and also there's no vscript properties on new created prop_dynamic

**Comment by DrinklyDram** [comment]
it's yours fgd error
![image](https://user-images.githubusercontent.com/40040054/154805230-40fd1ae1-a1c9-4fe5-b46e-4ca585fc6519.png)

**Comment by nuclearsilo583** [comment]
Could you help me how can I fix this. Verified SDK and csgo?

**Comment by DrinklyDram** [comment]
try to
