### ISSUE TITLE
[Bug] "ignorenormals" property causes prop_statics to appear fullbright in lighting preview mode

### ISSUE THREAD

**Issue by Fishke1** [ficool2/HammerPlusPlus-Issue-Tracker#23]
When you enable the property "Ignore surface normal for computing vertex lighting" on prop_statics and do a lighting bake, the affected models appear fullbright.

![Screenshot 2022-01-22 143907](https://user-images.githubusercontent.com/58330946/150638918-8998b547-9cf8-452a-9f62-d4f8acf45de1.jpg)

MP2013, Hammer++ build 8853

**Comment by ficool2** [comment]
Fixed in the next build
