### ISSUE TITLE
[Feature Request] Auto-creating prop_dynamic modelscale keyvalue

### ISSUE THREAD

**Issue by Luffaren10** [ficool2/HammerPlusPlus-Issue-Tracker#232]
This is a small request to make prop_dynamic modelscale a bit smoother to edit.

Currently you need to this before being able to tweak the modelscale:
-- Turn off SmartEdit
-- Add the modelscale keyvalue
-- Apply

Would it be possible to auto-create the keyvalue, either upon creating the prop_dynamic or when SHIFT/CTRL+mousewheel scrolling?
Could something also be done to prevent the property-line from being indicated as red/unknown?:
![image](https://user-images.githubusercontent.com/36668214/154827882-91e0b79c-d9e6-4f84-aed4-801abf4e0568.png)

**Comment by DrinklyDram** [comment]
edit your fgd

**Comment by Luffaren10** [comment]
Editing the .fgd does indeed work just fine to get around it.
I suppose this is more a request to make it default/inherently-added by H++, since modelscale editing support was added.

Why have all the end-users jump the extra hurdles to access a functionality that was added? 🐤

**Comment by ficool2** [comment]
FGD fixes are out of scope for H++ for compatibility reasons
