### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TheShab47** [ficool2/HammerPlusPlus-Issue-Tracker#234]
Can a shortcut be added to toggle between 15 degree turning and regular turning? I find my self turning it off sometimes and it would just be easier if there was a shortcut to toggle it.

**Comment by Moltard** [comment]
Hammer++ and Hammer both have the '15 degree rotation', and they both have the key **Alt** that you can hold to be able to freely rotate.

So there is no need to add anything new. Just tick the '15 degree rotation' setting, and when you need to rotate by less than 15 unit (like 1 unit), hold Alt
