### ISSUE TITLE
[Feature Request] Toggleable warning when manipulating brushes with texture lock enabled

### ISSUE THREAD

**Issue by GabeMacken** [ficool2/HammerPlusPlus-Issue-Tracker#241]
Enabling texture lock can be useful for certain tasks, but in some cases, it can be left enabled by mistake and lead to distorted or badly-scaled textures requiring a manual fix later. This is particularly prevalent with new/inexperienced users who may not be aware such a feature exists, but it causes problems even for experienced mappers if left on by accident.

I propose adding a setting to enable a warning or pop-up of some kind when texture lock is enabled and/or when brushes are manipulated with it. The texture lock buttons could also potentially be highlighted in red or some other bright color to make it more obvious that they are selected.

**Comment by MARK2580** [comment]
I have been building maps since 2010, for all these years maybe three times I have encountered such a problem. I think you should just be more careful.

**Comment by ficool2** [comment]
Mark sums it up perfectly, having a warning is just intrusive and it's one thing you just have to learn to be aware of
