### ISSUE TITLE
[Feature Request] Dark UI theme - or use windows UI colours

### ISSUE THREAD

**Issue by WormSlayer** [ficool2/HammerPlusPlus-Issue-Tracker#250]
I swear this was listed as a feature in the original version, but it never worked for me?

**Comment by pablogonzales2009** [comment]
Please, where is it??
The image still exists: [link](https://ficool2.github.io/HammerPlusPlus-Website/images/features_ui.png) and 
[was in the features tab!](https://user-images.githubusercontent.com/66168769/156235115-36ba6326-3449-4d4a-956d-7e0eaf5693ed.png)

**Comment by meatspace** [comment]
Yes, you must install a custom windows theme.
Setting windows 10 to dark for instance will not work.
So use something like UltraUXThemePatcher to patch your windows to allow install of custom themes.
Then search deviantart or something to find theme files. The exact theme in ficool's picture is called Penumbra10

**Comment by ficool2** [comment]
Dark UI will only work with a custom windows theme, it is impossible to support it natively due to how old Hammer's UI system is
