### ISSUE TITLE
[Feature Request] Resize VisGroups tool panel

### ISSUE THREAD

**Issue by WormSlayer** [ficool2/HammerPlusPlus-Issue-Tracker#251]
So much empty space on the tool panel, that could be used to make the visgroups list easier to read.

**Comment by WormSlayer** [comment]
I never realised before, but I can un-dock the tool panel, resize it, then dock it again. Cant resize them while docked though, only move them.

**Comment by MARK2580** [comment]
you can move any element of the panels on the right and the buttons on the top in this way, this functionality is even in the standard hammer (sorry for the lags, this only happens when recording)

https://user-images.githubusercontent.com/11617079/156093097-886454c7-f421-4ba4-aa7b-2912089ace33.mp4

**Comment by WormSlayer** [comment]
Yeah you can move them, but only resize them when they are undocked.
