### ISSUE TITLE
The 3D skybox preview doesnt seem to work?

### ISSUE THREAD

**Issue by WormSlayer** [ficool2/HammerPlusPlus-Issue-Tracker#252]
I've tried it on lots of maps, but the show preview button doesnt seem to do anything.

**Comment by MARK2580** [comment]
https://youtu.be/feOO9c5Ibzs
you must turn the 3d skybox into an instance for the preview to work correctly.  please watch the video.

**Comment by WormSlayer** [comment]
Oh my bad. The video doesnt say anything about instancing the skybox though?

**Comment by MARK2580** [comment]
> Oh my bad. The video doesnt say anything about instancing the skybox though?

https://youtu.be/vtDtRaCAJz4?t=338  ok, i just answered from my phone, here you can see how to enable 3d skybox

**Comment by WormSlayer** [comment]
Tried it on a Half-Life 2 map, the combine citadel model doesnt get rendered, I think because once the skybox is scaled up x16, its too big and/or far away.

**Comment by MARK2580** [comment]
> Tried it on a Half-Life 2 map, the combine citadel model doesnt get rendered, I think because once the skybox is scaled up x16, its too big and/or far away.

I have the same. Sometimes it is, sometimes it isn't. While it's all "crutches".
