### ISSUE TITLE
[Bug] Holding Shift while 'Default to 15 degree rotations' is on doesn't enable free rotation

### ISSUE THREAD

**Issue by ultr4nima** [ficool2/HammerPlusPlus-Issue-Tracker#253]
While 'Default to 15 degree rotations' is on, holding Shift while rotating does not allow you to rotate with free rotation (as in without locking to 15 degree angles), unlike old Hammer.
(Side note: On both old Hammer & Hammer++, holding Alt allows you to rotate freely regardless of the 15 degree option being on,  exactly like how Shift should)

**Comment by ficool2** [comment]
Intentional, being able to duplicate while rotating is useful
