### ISSUE TITLE
[Bug, 8860] Blank space in Toolbar

### ISSUE THREAD

**Issue by Kiglirs** [ficool2/HammerPlusPlus-Issue-Tracker#273]
I have a blank space in my toolbar that is taking a lot of space. I might suspect it gets bigger on everytime i open it, but i have doubts on that.

![image](https://user-images.githubusercontent.com/29353662/158652078-bff52171-6b15-4890-8622-4cfecd42bdc0.png)

My OS is Windows 11, i might think this is what create this bug.

**Comment by MARK2580** [comment]
Just drag them to the right place. But yes, Win11 is most likely to blame here, I advise you not to use this raw operating system at all for the next year.

**Comment by Kiglirs** [comment]
I was about to start the debate, buuuut i won't. 
Yeah, i gues i could drag, but last time i did it it went back with some blank space some time later.

I guess i'll have to live with that bug

**Comment by MARK2580** [comment]
> I was about to start the debate, buuuut i won't. Yeah, i gues i could drag, but last time i did it it went back with some blank space some time later.
> 
> I guess i'll have to live with that bug

The fact is that I have never had such a problem on win10 with more than one version of hammer++. I have seen error messages with the interface more than once and all such users were exactly win11.

**Comment by ficool2** [comment]
Can't fix Windows 11-related issues as I don't have that OS installed
