### ISSUE TITLE
bug: "Serious Corruption Error" in Build: 8853, plus file recovery error

### ISSUE THREAD

**Issue by JubJubWebus** [ficool2/HammerPlusPlus-Issue-Tracker#28]
Encountered a "serious corruption error" in Build:8853 while the program was running Idle on my laptop.
Then, during file recovery, it encountered another issue

![Capture](https://user-images.githubusercontent.com/59837496/150646377-a11caacb-ed73-491a-865c-d148dd4208d5.PNG)

Mapping for tf2.
[pl_alongside_a5a.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7918706/pl_alongside_a5a.zip)

 ̶C̶o̶u̶l̶d̶n̶'̶t̶ ̶f̶i̶n̶d̶ ̶t̶h̶e̶ ̶.̶m̶d̶m̶p̶,̶ ̶b̶u̶t̶ ̶I̶ ̶c̶a̶n̶ ̶c̶e̶r̶t̶a̶i̶n̶l̶y̶ ̶t̶r̶y̶ ̶a̶n̶d̶ ̶p̶r̶o̶v̶i̶d̶e̶ ̶i̶t̶ ̶i̶f̶ ̶d̶i̶r̶e̶c̶t̶e̶d̶ ̶t̶o̶ ̶i̶t̶s̶ ̶l̶o̶c̶a̶t̶i̶o̶n̶.̶ ̶  The .latest .mdmp file I found is not the one associated with this crash (according to the timestamp).
also, I wasn't sure how to label this issue correctly, I apparently don't have any labels on the right bar with which to label, soooo.

**Comment by ficool2** [comment]
Not sure whats the cause of this, report this again if it happens consistently
