### ISSUE TITLE
[Feature Request] Estimated time when map will be compiled

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#283]
Hello,

Can be added some loading bar or % to know how long will map compile? :)

Thank you

EMINEM

**Comment by DrinklyDram** [comment]
just look at the console

**Comment by eminem0091** [comment]
where?

**Comment by DrinklyDram** [comment]
![image](https://user-images.githubusercontent.com/40040054/160280075-acc2add9-e8db-4162-ac06-483b88c77427.png)
0 = 0%;
10 = 100%;
 . = 10/3%

**Comment by eminem0091** [comment]
Yup true... but main point is how long it will take :)

**Comment by DrinklyDram** [comment]
if you are compiling the map with lighting then "Computing static prop lighting" will be the longest loading

**Comment by DrinklyDram** [comment]
Just see how fast the progress is and you will know approximately how much time is left.

**Comment by eminem0091** [comment]
I compiled maps already more than 1000 times and sometimes I just need to know how long it will take

**Comment by MARK2580** [comment]
This is technically impossible to do. Just wait and watch 0....1....2
