### ISSUE TITLE
[Feature Request] Drag both point of cutting at one

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#284]
Hello,

If its possible to make feature to drag both point when cutting at once

Thank you

EMINEM

![obrazek](https://user-images.githubusercontent.com/20126321/160270769-f7478afa-2abf-4d7c-9d69-2b914d7b23a7.png)

**Comment by MARK2580** [comment]
What for ? It doesn't make any sense. The cut tool will cut the brush anyway, even if the points are not exactly at the edges.

**Comment by eminem0091** [comment]
Yes but when you want move it quickly and cut it like "|" you need first take one and then second. Just idea to make it faster...

**Comment by MARK2580** [comment]
https://user-images.githubusercontent.com/11617079/160297546-f93836aa-2e1e-4bc0-ac74-44af1d5811ca.mp4

Learn the hotkeys and you will be happy, look how fast I do it, I don’t move anything if it doesn’t suit me, I just slide a new cut point and that’s it. Think about how annoying such a function will be if you need to cut something at an angle, for example.

**Comment by eminem0091** [comment]
Thank you for your time and endless help :)
