### ISSUE TITLE
[Feature Request] Mirror tool brushes

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#285]
Hello,

If its possible to add mirror tool for brushes. I was not able to find it.

Thank you :)

EMINEM

![obrazek](https://user-images.githubusercontent.com/20126321/160271121-9de29815-7663-4a14-bd70-670840b23390.png)

**Comment by DrinklyDram** [comment]
you can just rotate this brush 90 degrees

**Comment by DrinklyDram** [comment]
or if you want to mirror a brush just scale it by -1 on the desired axis
https://user-images.githubusercontent.com/40040054/160279695-3709f431-187c-4729-aec5-9d78b1eb5ffe.mp4

**Comment by MARK2580** [comment]
Ctrl+L / Ctrl+I

**Comment by eminem0091** [comment]
thank you guys :)
