### ISSUE TITLE
[Feature Request] After map saved, save also camera position

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#286]
Hello,

If its possible then after save map also save camera position

For example: Saved here

![obrazek](https://user-images.githubusercontent.com/20126321/160271904-f9c70bf8-b8de-41d3-b2d1-ae009b4f291e.png)

But after loading map again camera is here

![obrazek](https://user-images.githubusercontent.com/20126321/160271923-ceaf7329-a305-4ed9-aa2e-2f7399a01c17.png)

Thank you

EMINEM

**Comment by MARK2580** [comment]
Create a camera (Shift+C) , any standard Hammer saves the position of the last selected camera, don't clog the report, read the editor's documentation from the beginning.

**Comment by eminem0091** [comment]
sorry my bad
