### ISSUE TITLE
[Feature Request] Not possible to move prop behind brush

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#287]
Hello,

If posible to add somewhere button to not be enable to move prop under ground but it will stop after touching ground, wall,ceiling

![obrazek](https://user-images.githubusercontent.com/20126321/160272137-e6ca911d-9012-4280-9c77-d7068790c3b5.png)

Thank you :)

EMINEM

**Comment by MARK2580** [comment]
There is such functionality, I see no reason to add something else.
![SfySnYIurk](https://user-images.githubusercontent.com/11617079/160297019-b1c6b2f7-3fcf-4cdb-91dd-7fca364de1d6.png)

**Comment by eminem0091** [comment]
maybe you are right
