### ISSUE TITLE
[Feature Request] Before compile set commands for game

### ISSUE THREAD

**Issue by eminem0091** [ficool2/HammerPlusPlus-Issue-Tracker#288]
Hello,

its possible to add commands here before compiling map? For example bot_quota, mp_freezetime etc etc

![obrazek](https://user-images.githubusercontent.com/20126321/160273228-3df677c4-b0e6-4454-a13c-d6478e84c330.png)

Thank you

EMINEM

**Comment by MARK2580** [comment]
I can't figure out WHY??? If you need something like this, just create another line at the beginning and use -hijack as done in the last paragraph, again you are polluting the report list with your messages.

**Comment by eminem0091** [comment]
Thank you
