### ISSUE TITLE
Model Browser - No Ground issue

### ISSUE THREAD

**Issue by BerntA** [ficool2/HammerPlusPlus-Issue-Tracker#3]
Build: 8852
Game: Source SDK 2013 MP

I had this issue in 8849, and it is still in the latest version, basically checking 'No Ground' or possibly any option in the model browser panel does not persist for every model when you edit the search field, click a different folder, ex:
![image](https://user-images.githubusercontent.com/10424971/150589129-5cd682dd-992d-425a-9f25-51182c42e837.png)
it would also be nice to have an option to set no ground by default

**Comment by ficool2** [comment]
Fixed in the next build
