### ISSUE TITLE
[Bug] CS:GO prop_dynamic improper scaling preview

### ISSUE THREAD

**Issue by 18swenskiq** [ficool2/HammerPlusPlus-Issue-Tracker#30]
In CS:GO, prop_dynamic cannot be scaled with modelscale unless it has a bone. The Hammer++ preview always allows it to appear as scaled even if it can't be. It might also be somewhat beneficial to separate modelscale and uniformscale, as for instance uniformscale only works on prop_static and will do nothing on prop_dynamic and prop_physics

**Comment by ficool2** [comment]
Fixed in next build
