### ISSUE TITLE
TF2 Working with displacements 8854

### ISSUE THREAD

**Issue by neilstottler** [ficool2/HammerPlusPlus-Issue-Tracker#31]
[hammerplusplus_20220122_133757_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7919032/hammerplusplus_20220122_133757_1.zip)

Was working with about 4 displacements raising geo on the horizontal plane with the shift + left click.

**Comment by ficool2** [comment]
Fixed in next update
