### ISSUE TITLE
[Feature Request] Sprite Browser

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#310]
seeing as the `sprites` folder is excluded from the normal material list by default, I think it'd be good for sprites to get their own material browser. I would think this should be fairly easy to distinguish, as there's already a `sprite` KV type in FGDs.

**Comment by MARK2580** [comment]
This is the first time I hear that sprites are excluded from the texture browser. Only model textures are excluded from the browser.

![VdV3emQTD9](https://user-images.githubusercontent.com/11617079/163489313-02811771-1cc5-4f7b-ac57-759a042fbf59.png)

**Comment by Kestrelguy** [comment]
...that's a bit odd. I know how to enable/disable them, but I don't recall having messed with that...
