### ISSUE TITLE
[Feature Request] Option to move the camera in 3D View with arrow keys

### ISSUE THREAD

**Issue by Swarped** [ficool2/HammerPlusPlus-Issue-Tracker#32]
Hello! I noticed that it's not possible to move in 3D View with arrow keys, I even checked in the Keybindings and the arrow keys are binded to Camera "Strafing", but it doesn't do anything. I even changed the keybindings for moving objects. Thanks

**Comment by Iridium-77e** [comment]
I could be off base with this, but I've heard that it's a stylistic choice, as well as it conflicting with the minor adjustments that you can do with the arrow keys.

**Comment by ficool2** [comment]
Tools -> Options -> 2D View -> Untick "Nudge Objects"
