### ISSUE TITLE
[Bug] Run Map [Expert] config not saving parameters properly

### ISSUE THREAD

**Issue by retr0mod8** [ficool2/HammerPlusPlus-Issue-Tracker#33]
Hammer++ seems to not properly save the parameters for the "Run Map [Expert]" Dialog. When i add the directory path parameter for the `-game` command, it works fine, but closing Hammer++ then opening it again replaces the directory path and everything after with a single backslash.

![before](https://user-images.githubusercontent.com/69282617/150652687-85f7c9f1-7625-4e28-9d39-6afa6a91b8f8.PNG)
![after](https://user-images.githubusercontent.com/69282617/150652689-4f14b90b-5257-4c7e-87bc-3194cd50f138.PNG)

Parameters Before: `-allowdebug -windowed -game "D:\SteamLibrary\steamapps\common\GarrysMod\garrysmod" +map $file`
Parameters After:  `-allowdebug -windowed -game \`

HPP Build Number: 8854
HPP Game: Source SDK 2013 Multiplayer

**Comment by MARK2580** [comment]
By the way, this problem was still in all previous versions, but I forgot about it, because. using cmd

**Comment by ficool2** [comment]
Fixed in next build
