### ISSUE TITLE
add your hammer++ to nexon games

### ISSUE THREAD

**Issue by ADVABonnie** [ficool2/HammerPlusPlus-Issue-Tracker#342]
hello i have a big request see we have a closed project from devs nexon they cooperate with valve they have 3 projects related to them counter-strike online, counter-strike online 2, counter-strike nexon studio. If you reply to the messages we need a hammer++ for Counter-Strike Online 2 version and with working lighting we are porting the maps now 1 by no lighting but using a text document to match the sunlight to using mat_fullbright 1 please let me know you can email this person about such questions organnerx#2405. in CSO2 it was possible to create maps with the size of the city, so in CSO2 there are 2 maps of the city BigCity Pve and BigCity PVP
these are 2 original maps from nexon from 2013 and 2018
![cso2_0000](https://user-images.githubusercontent.com/69756761/170875235-e13626ff-7eb7-422d-a4b5-db47a3975189.jpg)

**Comment by MARK2580** [comment]
This will definitely never happen, corny due to the lack of source codes for these games.

**Comment by ADVABonnie** [comment]
> This will definitely never happen, corny due to the lack of source codes for these games.

This can be done if the usual css hammer ++ remove the restrictions on the size of maps for cso2 and find out what causes the problem of baking maps from css or csgo they just look like lighting and shadows are confused and confused their position stability https://youtu.be/YJR4Apb9K7Q take a look at this video for example how it looks like in reality this is a map from the 2017 Chinese version of the game but not for the Korean version even though I have the old 2014 Korean version

**Comment by MARK2580** [comment]
> > This will definitely never happen, corny due to the lack of source codes for these games.
> 
> This can be done if the usual css hammer ++ remove the restrictions on the size of maps for cso2 and find out what causes the problem of baking maps from css or csgo they just look like lighting and shadows are confused and confused their position stability https://youtu.be/YJR4Apb9K7Q take a look at this video for example how it looks like in reality this is a map from the 2017 Chinese version of the game but not for the Korean version even though I have the old 2014 Korean version

judging by this video it's generally cs1.6 😸

**Comment by ADVABonnie** [comment]
But however, we need a version of hammer ++ where there is no restriction on the engine from css, but just to cut it out of hammer ++ so that you can create maps for xo2 with the size of the city
