### ISSUE TITLE
[Feature Request] Add Dark Mode to Hammer++

### ISSUE THREAD

**Issue by EuroSzymon** [ficool2/HammerPlusPlus-Issue-Tracker#343]
Please add the possibility of setting **the dark UI for comfortable night work** and **for the user's personal preference to appearance**, _because_ **_not everyone prefers_** to the _standard light hammer mode_ so **in Hammer++ add _Dark mode._**

**Comment by thetomix7** [comment]
Yeah, a dark mode would be great it's kind of a hassle to get custom windows themes working.

**Comment by WormSlayer** [comment]
+1

**Comment by DevTimmOfTO** [comment]
+1

**Comment by ghost** [comment]
I'm pretty sure Hammer++ and Hammer uses the default windows UI library that's used for every application. This isn't possible without theme patching Windows as far as I know

Though, I'm pretty sure the website mentioned dark mode at some point, I tried looking in the options and didn't find any, so I assume ficool just meant that it supports theme patching
