### ISSUE TITLE
Hammer++ crashes sometimes when editing displacements

### ISSUE THREAD

**Issue by FrostyHoneyJuicy** [ficool2/HammerPlusPlus-Issue-Tracker#35]
[hammerplusplus_20220122_230057_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7919289/hammerplusplus_20220122_230057_1.zip)

Apparently, when editing displacements, Hammer++ sometimes crashes.

**EDIT:**
So far Hammer has crashed on me when:
- Pressing CTRL+SHIFT on displacements
- Selecting displacements
- Painting geometry
- Painting alpha

**Comment by ficool2** [comment]
Fixed in next update
