### ISSUE TITLE
[BUILD 8861] Shaded Textured Polygons doesn't work.

### ISSUE THREAD

**Issue by HolzstockG** [ficool2/HammerPlusPlus-Issue-Tracker#356]
As above, when you select it, it looks just like Textured mode plus it ERASES when selected blend textures (if you paint on blend texture, then this painted texture on top of first will be erased). They come back after switching modes. Also, there is no preview bar under camera bar (for compiling lighting) in 3D view as previous to that version.

**Comment by ficool2** [comment]
Fixed in 8862
