### ISSUE TITLE
[Build 8861] Water display broken

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#358]
The first thing I noticed as soon as I ran the updated hammer++ was broken water... I guess no further explanation is needed.

https://user-images.githubusercontent.com/11617079/175810071-b787a4ff-3119-4920-9e72-221392bb96d3.mp4

**Comment by HolzstockG** [comment]
Also textures change resolution when rotating 3D View

**Comment by CopCorvette** [comment]
Same here [TF2] 
![image](https://user-images.githubusercontent.com/71981755/175829185-30fdb92f-4864-4c83-9c50-f8a642f29ea7.png)

**Comment by HolzstockG** [comment]
This is bug (those walls are displacements)
![image](https://user-images.githubusercontent.com/34598047/175829248-a162fc38-980a-4727-95ee-dd8e7a2d1600.png)
After slighty rotating and moving to different position it shows properly (CSGO)  
![image](https://user-images.githubusercontent.com/34598047/175829288-e0ed9be7-4fc2-4b06-a591-d98211546897.png)

**Comment by CopCorvette** [comment]
Bad news 😢
![image](https://user-images.githubusercontent.com/71981755/175829655-ec73d6a5-e064-4dc1-a9d3-172f06c38c9d.png)

**Comment by ficool2** [comment]
Fixed in 8862
