### ISSUE TITLE
Crash when editing props while walkable area is on?

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#36]
was cloning and editing some static props with the "walkable prop surface" thingy toggled on. I don't even know if that's what caused the crash, but that's all I was doing when it crashed.
[walkable prop crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7919637/walkable.prop.crash.zip)

**Comment by ficool2** [comment]
Should be fixed next update
