### ISSUE TITLE
[Bug] 8861 - Entity class changing after copying outputs

### ISSUE THREAD

**Issue by Moltard** [ficool2/HammerPlusPlus-Issue-Tracker#360]
New post about the issue, which didnt get totally fixed in 8861

See https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/309 for the issue description in 8860

------

I found one exact method to break entities

It's very dangerous, as it involve unselecting entities while in the input tab (or output,visgroup,flag), and selecting them again.
Which you can do without really noticing

**__How to break classname in Hammer++__**

What you need:
A **entity_2** that has an output targeting **entity_1**
The **entity_x** can be any entity in your map. It doesnt matter

> **Step 01:** Select `entity_x`
> **Step 02:** Go in the `entity_x` input tab
> **Step 03:** Unselect the `entity_x` (click in the void in the 3D View or 2D View)
> **Step 04:** Select the `entity_1` (you are in the "Input" tab)
> **Step 05:** Double click on the source input, to go to `entity_2`
> **Step 06:** You are now in `entity_2` "Output" tab
> **Step 07:** Go to the "Class Info" tab
> **Step 08:** Go back to the "Output" tab
> **Step 09:** __/!\\__ Here you **can double click literally any of the output** available on `entity_2` , to go to the entity targeted
> **Step 10:** You are now on the **entity** that was **targetted by the output**
> **Step 11:** Go to the "Class Info" tab
> **Step 12:** __/!\\__ The **entity you are on is starting to break** and is becoming of the type of `entity_2`

Note: **the initial entity used in the step 1 to 3 could be any entity in your map**, what matters is that you unselected an entity while the input tab was open

Here a video

https://cdn.discordapp.com/attachments/443090575017902080/990757408345321482/2022-06-27_01-15-09_new.mp4

----

Step 01-03 are the most important one. And it doesnt only work with input tab, it work on outputs, flags and probably visgroup. It seems safe if you unselect the entity when in class info.

**Comment by ficool2** [comment]
Fixed in 8862
