### ISSUE TITLE
fatal error loading pixel shader phong_ps30 (0a154140)

### ISSUE THREAD

**Issue by C-InfDef** [ficool2/HammerPlusPlus-Issue-Tracker#361]
I am using Hammer++ CS:GO version for Portal 2 without the CS:GO SDK and upon searching cube in the model preview, it crashes the application telling me that underground_weighted_cube.mdl is corrupt despite showing no apparent issues with other applications such as the game itself or Official Hammer.

**Comment by damqn4etoBG** [comment]
Yea, me too, I have the CS:GO SDK installed and everything and it says that models/props/metal_box is corrupted and needs to be removed.

**Comment by merkisten** [comment]
I have that problem too.
![theproblem](https://user-images.githubusercontent.com/108378146/176503809-6eef2f5b-6d8a-4dc0-8f86-65c73b14df4f.JPG)

![theproblemalso](https://user-images.githubusercontent.com/108378146/176503941-3f231973-e200-4e08-99d2-3e5d10595663.JPG)

**Comment by ficool2** [comment]
Fixed in Build 8862
