### ISSUE TITLE
Sprinkled props can't decide if they exist or not [8854, TF2]

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#37]
Props created with the sprinkle tool seem to be finicky about their existence. They blink out near the edge of the camera, and they're hard to select. This isn't the case for the exact same type, model, and skin of prop placed normally. Successfully selecting them and viewing their properties seems to resolve the issue.
update: they're as easy as any prop to select on the 2D views, it's just 3D views that are so finicky.
![props self-hidden](https://user-images.githubusercontent.com/97305860/150663249-7d8b18e9-c99e-4402-9761-277f12465ccf.png)
![props showing](https://user-images.githubusercontent.com/97305860/150663250-c9dabda8-f35c-43d3-ba66-9fb95c06c8f4.png)

**Comment by ficool2** [comment]
Fixed in next update
