### ISSUE TITLE
[Source 2013 MP] 0xc0000005 exception when opened Model Browser

### ISSUE THREAD

**Issue by nikita488** [ficool2/HammerPlusPlus-Issue-Tracker#38]
![image](https://user-images.githubusercontent.com/6237881/150669934-6efb00dd-9e34-48e8-af93-ff336c61d686.png)
Got this error when opening the model browser to choose a model for prop_static.
Note that I have a lot of games mounted inside gameinfo.txt (CS Source, Day of Defeat, HL2 Episodes, L4D 1 and 2 with all DLCs, Portal 1 and 2 with all DLCs, GMod)
[hammerplusplus_20220123_110421_1.mdmp.txt](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7920034/hammerplusplus_20220123_110421_1.mdmp.txt)

**Comment by ficool2** [comment]
L4D2 and Portal 2 models will crash SDK 2013, theres no way to fix this other than removing those assets or converting them all to older formats by decompiling + recompiling
