### ISSUE TITLE
Click and hold select broken/missing

### ISSUE THREAD

**Issue by vrad-exe** [ficool2/HammerPlusPlus-Issue-Tracker#382]
In Hammer, you can click and hold in the 3D view to cycle through selecting each object under the cursor. In Hammer++ this appears to no longer work, making it difficult to select overlapping objects.

**Comment by ficool2** [comment]
This was replaced by middle mouse click in the 3D view (or shift + mouse click if using Mouse3 camera mode), the page up/down buttons also work
