### ISSUE TITLE
[Bug? CSGO/Portal2 Particle Browser] Hammer++ crashes when opening particle browser

### ISSUE THREAD

**Issue by Equalizer5118** [ficool2/HammerPlusPlus-Issue-Tracker#387]
I am using hammer++ for CSGO however I use it for Portal 2. I'm trying to create a info_particle_system but every time I open the particle browser it crashes with an EXEPTION_ACCESS_VIOLATION. If it helps, the exception code is 0x0000005.
What does this mean, how do I fix it?
Here's an image:
![1664684467742833221348455842825](https://user-images.githubusercontent.com/113145248/193437704-2c0a8374-06a9-43c1-8c3b-8889f0154a2e.jpg)

**Comment by TabTray** [comment]
having the same issue, hopefully this gets patched

**Comment by theEthonic** [comment]
I am also having this issue. Hopefully It gets fixed.
