### ISSUE TITLE
[Bug] Texture glitch when trying to move solids nearby enitites

### ISSUE THREAD

**Issue by BerntA** [ficool2/HammerPlusPlus-Issue-Tracker#4]
Build: 8852
Game: Source SDK 2013 MP

Got jump scared by this:
![image](https://user-images.githubusercontent.com/10424971/150589862-cd3045ae-a267-4dce-a11d-079f993bbab4.png)
when pressing and holding left mouse btn here @ yellow square:
![image](https://user-images.githubusercontent.com/10424971/150589978-a8a2ea88-696d-4a86-9a91-adad15b350d4.png)
applies to any ent:
![image](https://user-images.githubusercontent.com/10424971/150590064-35d2f174-245f-45c3-ba17-048034620c92.png)
![image](https://user-images.githubusercontent.com/10424971/150590144-e330ef8c-bc0b-4925-9cbd-6bdfd4cb871b.png)

**Comment by BerntA** [comment]
Even worse now, not doing anything, simply have a transparent brush nearby some ent
![image](https://user-images.githubusercontent.com/10424971/150591113-8f64a140-72a0-460b-b20f-87698d7f62a5.png)
from underneath its fine
![image](https://user-images.githubusercontent.com/10424971/150591213-38fbe797-7473-430c-b0ce-34b1d3099a4b.png)

**Comment by ficool2** [comment]
Fixed in next update
