### ISSUE TITLE
Add option to enable/disable 3D-gizmo (X-toggle)

### ISSUE THREAD

**Issue by Luffaren10** [ficool2/HammerPlusPlus-Issue-Tracker#42]
This is a feature request for the X-toggle on selected objects in the 3D view.
Could an option be added to enable/disable the gizmo mode? (far right)

This would make things more smooth to work with for non-gizmo users, as you currently need to press X 3 times in total to go between the modes.

It may be a small thing, but would be very welcome to see added.

![image](https://user-images.githubusercontent.com/36668214/150690017-dc3a70a6-67ff-4655-b4db-7d9f3a76285c.png)

**Comment by celisej567** [comment]
> Это запрос функции для переключения X на выбранные объекты в 3D-представлении. Можно ли добавить опцию для включения/выключения режима gizmo? (крайний справа)
> 
> Это сделало бы работу более удобной для пользователей, не являющихся gizmo, так как в настоящее время вам нужно нажать X 3 раза в общей сложности, чтобы перейти между режимами.
> 
> Это может быть мелочью, но было бы очень приятно, если бы вы добавили.
> 
> ![изображение](https://user-images.githubusercontent.com/36668214/150690017-dc3a70a6-67ff-4655-b4db-7d9f3a76285c.png)

I'm certainly not a very important person and no one asked my opinion, but this idea is not really required. In a normal hammer, you had to hit X 2 times, and the difference between 2 and 3 clicks is not significant.

**Comment by Luffaren10** [comment]
@celisej567
As someone who's always been using the X-toggle extensively it does infact make a difference. Significant enough to open this request. 🤓 

Having an ON/OFF switch is way simpler than having to cycle through all modes every time.
At the same time the new gizmo doesn't really offer anything that the old mode couldn't already manage.

I have no qualms at all with keeping the new gizmo enabled by default as-is. 
All i'm asking for is the ***_option_*** to turn it off, hidden away in the "_options > hammer++_" section or whatever.

**Comment by ficool2** [comment]
Added in next update

**Comment by SethTooQuick** [comment]
Might be better to have it on one of the two existing modes and just have a tool bar icon to enable disable. Though the button to swap from the gizmo modes would have to be changed, or maybe do a hybrid gizmo of all 3 like blender can do.
