### ISSUE TITLE
[Bug] grass sprite won't disappear after you change the texture

### ISSUE THREAD

**Issue by GXP10** [ficool2/HammerPlusPlus-Issue-Tracker#44]
If you applying texture with grass sprite on displacement and then reapply another texture with no grass sprite again, the grass wont disappear until you reload the vmf.
before
https://cdn.discordapp.com/attachments/420095739562295296/934758959053684766/unknown.png
after
https://cdn.discordapp.com/attachments/497028674810281986/934879866518659072/unknown.png

**Comment by ficool2** [comment]
Fixed in next build
