### ISSUE TITLE
[Bug] Modifying a brush (that has a tool texture) while 'Show tool texture' is unticked make it invisible

### ISSUE THREAD

**Issue by Moltard** [ficool2/HammerPlusPlus-Issue-Tracker#48]
As the title say.

Not really a big issue, but if you make a brush with a tools texture (like toolsskybox), and then edit it (rotate, resize,..) while 'show tool texture' is disabled, then when you do the resize / rotate, the brush is invisible, so you cannot see what you are doing. it reappear after the modification is done.

see imgur below
https://imgur.com/a/RYwRt2B

**Comment by ficool2** [comment]
Fixed in next update
