### ISSUE TITLE
[Bug, 8854, TF2] Crash When Clipping (While Zoomed Out?)

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#49]
Had a crash happen while trying to clip a wall. Only thing I can think of that's different from when it went perfectly fine is that I happened to be zoomed out kinda far.
[zoomed Hammer crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7921751/zoomed.Hammer.crash.zip)

**Comment by ficool2** [comment]
Probably already fixed on build 8855
