### ISSUE TITLE
Crashing when creating env_sprite_clientside

### ISSUE THREAD

**Issue by Yashirmare** [ficool2/HammerPlusPlus-Issue-Tracker#5]
Build: 8852
Game: Source SDK 2013 MP

If you attempt to create a env_sprite_clientside H++ will crash with an access violation. (Exception code: 0xc0000005)
Has been an issue since the original release. 

[Included dump, however useful it may be. ](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7916185/hammerplusplus_20220121_193521_1.zip)

**Comment by ficool2** [comment]
Should be fixed in the next build

**Comment by Yashirmare** [comment]
Issue still exists as of build 8854.
