### ISSUE TITLE
[Bug, 8854, TF2] Transparent Textures and Displacements Facing Lights Confuse Lighting Preview

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#50]
The lighting preview function seems to be confused by textures that don't cast shadows and by displacements.
If I make a brush and texture it with Nodraw, Block Light, or an opaque normal texture, put a light on it, then bake in a radius, a shadow is cast as normal. If I hide that brush and bake in a radius, the shadow goes away as expected, and if I unhide it and bake, the shadow returns. This all is exactly as it's supposed to work and is a fantastic addition to the editor.
However, if I texture the brush with a non-shadowing texture (such as Clip or `glasswindow002a`), or if I turn the light-facing side of the brush into a displacement, the preview seems to get confused. If there was already a shadow (because the brush used to have a texture that casts shadows), that shadow is maintained when I re-bake. If there wasn't a shadow, though, no shadow is cast. This last bit is supposed to happen for transparent textures, but not for displacements (which apparently cast shadows in both directions despite only being solid in one).
For transparent textures, there are a couple workarounds. If you undo or re-do a texture change, it seems to recalculate the shadows for that brush, causing it to not cast shadows anymore. So if you just changed the texture, undoing and redoing the change will work. If it's been transparent for a while, changing the texture and then undoing the change will work, too. It doesn't matter what you changed the brush to/from—it'll cast shadows properly when you bake, as long as I make the change. Alternatively, just moving the brush works. This only works on a per-brush basis, though. You need to revert or move each brush that shouldn't be casting shadows.
For displacements, on the other hand, there is no workaround, unless you wanna put a shadow-casting brush there that doesn't even serve any purpose for VRAD.

**Comment by ficool2** [comment]
Fixed in 8856
