### ISSUE TITLE
[Bug, 8855, CS:GO] Model browser crashes when trying to search for a prop.

### ISSUE THREAD

**Issue by GoldenKnight207** [ficool2/HammerPlusPlus-Issue-Tracker#52]
Anytime I open the model browser and try to search for a model, hammer instantly crashes. It also crashes anytime I try to click on a model and other times it crashes when loading the models. I can scroll through the models completely fine but its only when searching for or clicking on one when it crashes.

https://user-images.githubusercontent.com/98306091/150738553-81cab5f4-1ab9-43c2-a487-0d5f96803821.mp4

**Comment by ficool2** [comment]
Does this happen if you remove all custom content?

**Comment by GoldenKnight207** [comment]
> Does this happen if you remove all custom content?

It does not

**Comment by ficool2** [comment]
Send the crash dump

**Comment by GoldenKnight207** [comment]
[crashdump.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7929127/Dump.zip)

**Comment by ficool2** [comment]
Could you try this again on Build 8856 and see if it crashes, if it does, send the new crash dump

**Comment by GoldenKnight207** [comment]
It still crashes
[crashdump2.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7930233/crashdump2.zip)

**Comment by GXP10** [comment]
you probably crash because you didn't port the content properly from older game judging by the fact that there're antlion, alyx show in model viewer.

**Comment by ficool2** [comment]
It's crashing on a HL2 model, I'm not sure which one, unfortunately I can't fix crashes related to old models

**Comment by GoldenKnight207** [comment]
> It's crashing on a HL2 model, I'm not sure which one, unfortunately I can't fix crashes related to old models

I fixed it. I had to delete some models but luckily it was on some that I didn't need.
