### ISSUE TITLE
[Bug] Clicking "Open..." freezes program, making it unusable

### ISSUE THREAD

**Issue by GordonFreakman** [ficool2/HammerPlusPlus-Issue-Tracker#53]
When i click Open, the program tries to open the dialogue, it fails, and isn't focusable or closable, meaning i have to use task manager to close it out.

Source SDK Base 2013 Singleplayer
Build 8855

**Comment by ficool2** [comment]
I have no idea what causes this and I can't reproduce it. As a workaround you can disable "Fancy UI" in the Hammer++ options, and the dialogue will work
