### ISSUE TITLE
[Feature Request] Lighting Preview window as a Screen Element

### ISSUE THREAD

**Issue by WereTech** [ficool2/HammerPlusPlus-Issue-Tracker#54]
I find the window a bit annoying and taking up space in front of the 3d and 2d view. It would be nice if this could be a Screen Element so it can be merged into the sidebar with everything else. This would require a bit of tweaking of the window's layout, but imo would be really great to not have this in the way by default. You could also have the element greyed out if none of your views are set to 3D Lighting Preview. (Would be pointless to have it enabled if you couldn't even see what it did, and you would be locked out of doing anything while it compiles lighting if you clicked one of the Bake buttons by accident.)

**Comment by ficool2** [comment]
Hammer's UI would need a redesign to support this, and at the moment it's much work to do that
