### ISSUE TITLE
Collapsing an instance does not fix-up texture coordinates

### ISSUE THREAD

**Issue by iiboharz** [ficool2/HammerPlusPlus-Issue-Tracker#60]
![hammerplusplus_2022-01-24_14-28-44](https://user-images.githubusercontent.com/5212525/150801937-5d57d69e-987b-4e6c-beac-d165c5422853.gif)

I dunno if this is a feature request or a bug report - but you can see what's happening in the gif. I don't know if this is just a Hammer++ thing or if this happens in stock Hammer as well (if it is I've never noticed before.)

This is on version 8855 for SDK 2013 Singleplayer.

**Comment by ficool2** [comment]
I need a vmf of the problematic brush

**Comment by iiboharz** [comment]
This should be everything relevant.

[debug-stuff.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7929207/debug-stuff.zip)

**Comment by JamesT-W** [comment]
If I remember correctly, this happens sometimes when Texture Lock is disabled when you collapse the instance, something along those lines.

**Comment by ficool2** [comment]
Fixed in build 8858
