### ISSUE TITLE
[Bug] Texture Shift increment behave differently depending of the Windows language

### ISSUE THREAD

**Issue by Moltard** [ficool2/HammerPlusPlus-Issue-Tracker#63]
As the title say and as mentionned on Discord earlier,

Some people, who have their windows language to a different language can have issues with the texture shift

In the following example, the person has its language to **Turkish**
https://cdn.discordapp.com/attachments/917974334025375794/934996061515300964/2022-01-24_05-18-32.mp4

As it was also noticed months ago, it happened for a **german** user.

https://cdn.discordapp.com/attachments/111951182947258368/852631309784186910/unknown.png

some other quote onDiscord from back then:
 _"if windows language is set to german, it fucks up the texture rotation in hammer++"_
The cause would possibly be a different decimal separator used for numbers.

_"In German the comma rather than the period is used as a decimal separator and the dot is used as a thousands separator: 12.345,67 . The comma creates some unwanted space when used as in $12.345,67$"_

C# has function like this https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0 which allow to override the localization used by a whole app, but I dont know if C++ has an equivalent.

**Comment by ficool2** [comment]
Hopefully fixed in build 8856
