### ISSUE TITLE
[Bug] Lighting Preview update after applying a light color to 0,0,0 causes 'Serious corruption error'

### ISSUE THREAD

**Issue by NovaCanterra** [ficool2/HammerPlusPlus-Issue-Tracker#67]
I doesn't appear to happen if the light is black before the first bake but if you apply it while already in lighting preview and bake again, it immediately crashes hammer ++. 
One may ask why I made a black light... idk.
![unknown (2)](https://user-images.githubusercontent.com/20601559/150907764-1fd432b0-8c21-4821-83b0-911aab717653.png)

**Comment by Yankumo-Koishi** [comment]
I just couldn't figure out why u need to place a black light

**Comment by NovaCanterra** [comment]
> I just couldn't figure out why u need to place a black light

I'll be honest, it was late and I was tired

**Comment by ficool2** [comment]
Fixed in build 8857
