### ISSUE TITLE
[Bug] Textures disappear when stretching a brush

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#69]
When I stretch the brush, the texture on it temporarily disappears, which makes it very difficult to adjust the texture itself, it only appears when you release the mouse. For comparison, standard hammer and hammer++

https://user-images.githubusercontent.com/11617079/150936614-962256b3-5b31-4512-ade7-5ee4e08ac9d5.mp4

**Comment by ficool2** [comment]
Fixed in Build 8857
