### ISSUE TITLE
[Bug] Model browser thinks keys are being pressed

### ISSUE THREAD

**Issue by SuperSlimek** [ficool2/HammerPlusPlus-Issue-Tracker#70]
Occasionally model browser thinks keys like Ctrl/Alt/Shift are pressed, leading to unpleasant situations like not being able to select or rotate models

https://discord.com/channels/111951182947258368/111951182947258368/930562460090523689

**Comment by ficool2** [comment]
Should be fixed or atleast happen way less often in Build 8857
