### ISSUE TITLE
Support VTF Version 7.5?

### ISSUE THREAD

**Issue by 1mBubble** [ficool2/HammerPlusPlus-Issue-Tracker#71]
![image](https://user-images.githubusercontent.com/34455151/150958787-97ea15d4-bcd3-4488-9256-6402b3ccb1b9.png)
![image](https://user-images.githubusercontent.com/34455151/150958874-c60dbcb8-46fd-4436-b43f-59be659159d9.png)
If it's not difficult, can you implement support?

**Comment by MARK2580** [comment]
> ![image](https://user-images.githubusercontent.com/34455151/150958787-97ea15d4-bcd3-4488-9256-6402b3ccb1b9.png) ![image](https://user-images.githubusercontent.com/34455151/150958874-c60dbcb8-46fd-4436-b43f-59be659159d9.png) If it's not difficult, can you implement support?

2013 or csgo? Because 2013 only supports version 7.4 and it makes no sense to support 7.5. I recently encountered this myself.

**Comment by ficool2** [comment]
It's impossible to support version 7.4 under SDK 2013. Only the CSGO version supports 7.5
