### ISSUE TITLE
[Bug] Texture shift increments wrong

### ISSUE THREAD

**Issue by Berke111** [ficool2/HammerPlusPlus-Issue-Tracker#72]
https://user-images.githubusercontent.com/51463005/151017321-6cf013d0-080d-499f-9738-bbcdac1edb98.mp4 as can be seen from the video, there seems to be a problem while incrementing texture shift.

My issue was reported here before:
https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/issues/63
but the change logs only mentioned fixing German and Spanish, therefore, my issue goes unfixed in build 8856,
I have asked multiple friends of mine who use Turkish system language and they all reported the same issue so I know it should be caused by the system language, I don't know if I can give more info about this issue, if I can, tell me below.

**Comment by ficool2** [comment]
Hopefully fixed in Build 8857, if not I'll take a look again
