### ISSUE TITLE
[Bug] Vertex Tool create invalid solid when adding new vertices

### ISSUE THREAD

**Issue by Moltard** [ficool2/HammerPlusPlus-Issue-Tracker#73]
I mentionned this on discord,

In Hammer++, if you make a square brush and use the vertex tool to add extra vertices(to make a more complex shape), the brush will be invalid after adding a 7th vertice (from the top view perspective)

https://cdn.discordapp.com/attachments/111951182947258368/935573561689657374/Hammer_-__Untitled__-_Right_2022-01-25_17-32-56_new.mp4

Invalid solid structure (point off plane)
https://cdn.discordapp.com/attachments/111951182947258368/935573567842697276/unknown.png

Building the exact  same thing doesnt bug in normal Hammer

https://cdn.discordapp.com/attachments/111951182947258368/935574313556406322/Hammer_-__-_Textured_2022-01-25_17-37-28_new.mp4

No error
https://cdn.discordapp.com/attachments/111951182947258368/935574336646029363/unknown.png

-
Also one extra bug related to this. I merged back vertices of the broken solid, and after merging two vertices, an error happened (with calculation error). Likely a division by 0.

Here is the error and the mdmp in a zip
![image](https://user-images.githubusercontent.com/65123883/151030525-f36049db-8143-4c16-ae45-1692d71a9471.png)

[hammerplusplus_20220125_184043_1.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7935911/hammerplusplus_20220125_184043_1.zip)

**Comment by ficool2** [comment]
Fixed in build 8857
