### ISSUE TITLE
[Bug] breakable_surf has keyvalue error 1 even though it has only one textured face

### ISSUE THREAD

**Issue by RoxoFoxo** [ficool2/HammerPlusPlus-Issue-Tracker#75]
I'm using the 8856 build although it was happening on 8855 aswell, I'm using it for Counter-Strike: Source.

Just as the title says, I create a nodraw block, put a breakable glass texture on one side and on the breakable_surf keyvalues it has error 1, and it happens on any map, even on a new one.

![image](https://user-images.githubusercontent.com/69711760/151038948-9a85ed67-edcc-4509-82cc-4c19f80ebc8b.png)

**Comment by ficool2** [comment]
Fixed in Build 8857
