### ISSUE TITLE
[Feature Request] Add grid intensity slider for 2D grid

### ISSUE THREAD

**Issue by WunkaFaceball** [ficool2/HammerPlusPlus-Issue-Tracker#76]
2D grid intensity slider is a feature in regular hammer, but missing in H++. I prefer a less intense white/grey for the grid. I think I was able to edit something to get the value I wanted, but having it in the GUI might be appreciated by more.

**Comment by ficool2** [comment]
The setting was removed because it was incompatible with the color customization feature

Open hammerplusplus_settings.ini and change the Grid color under [Color] section
