### ISSUE TITLE
Crashing when creating env_sprite_clientside

### ISSUE THREAD

**Issue by Yashirmare** [ficool2/HammerPlusPlus-Issue-Tracker#79]
Build: 8856
Game: Source SDK 2013 MP

Issue was not fixed.

**Comment by ficool2** [comment]
Does this still happen on Build 8857? If so, send the crash dump

**Comment by Yashirmare** [comment]
Yeah, still happening.
[Dump](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7944573/hammerplusplus_20220126_191629_1.zip)

**Comment by ficool2** [comment]
There appears to be conflicting FGDs, can you check your game configuration and check if you have the correct ones mounted?

**Comment by Yashirmare** [comment]
Woops, had 2 base fgd's mounted. Having said that, after removing the extras it's still crashing.
[New dump in-case it helps](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7963770/hammerplusplus_20220129_133113_1.zip)

**Comment by ficool2** [comment]
Fixed in next update
