### ISSUE TITLE
[Bug, 8857, TF2] Crash When Destroying Numerous Displacements

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#80]
Tried destroying a number of displacements. Got a crash (with that 0xc00005 error or whatever) when I did so. They were a mix of powers 2 and 3, and the underlying brushes were a tad oddly shaped, but I don't think there were any particularly weird things going on.
When I booted up the autosave and tried to destroy the displacements, I had no problems (though there may have been one fewer displacement than when the cash happened).
[displacement destruction crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7938917/displacement.destruction.crash.zip)

**Comment by ficool2** [comment]
Should be fixed in build 8858
