### ISSUE TITLE
[BUG] func_monitor texture alignment bug

### ISSUE THREAD

**Issue by MilkywayM16** [ficool2/HammerPlusPlus-Issue-Tracker#81]
Build number: 8857
Game: SDK 2013 SP

Compiling a map that has a func_monitor will bug the monitor's view.

Bugged result (hammer++):
![image](https://user-images.githubusercontent.com/6911919/151113668-1aef3981-d098-4120-aca6-e53f20a29560.png)

Expected result (regular hammer):
![image](https://user-images.githubusercontent.com/6911919/151113616-1eb6afb5-8835-4c18-b9aa-a9f6c1c06309.png)

**Comment by ficool2** [comment]
Fixed in next update
