### ISSUE TITLE
[Feature Request] env_sun entity sprite (CSGO)

### ISSUE THREAD

**Issue by ItsPepperpot** [ficool2/HammerPlusPlus-Issue-Tracker#85]
Currently, the `env_sun` entity displays with a gray box in the CSGO version of Hammer/Hammer++.

![env_sun entity in the CSGO Hammer editor](https://i.imgur.com/0Utgbu8.png)

It would be nice to have the env_sun sprite back in the CS:GO SDK. :)
![env_sun sprite](https://developer.valvesoftware.com/w/images/4/43/Env_sun%28gmod%29.png)
Thanks again for all your great work.

**Comment by ficool2** [comment]
Out of scope, these are FGD-specific changes and not Hammer changes
