### ISSUE TITLE
Clipping tool bug

### ISSUE THREAD

**Issue by Ulqxiorra** [ficool2/HammerPlusPlus-Issue-Tracker#86]
When I try to use the "Clipping Tool" the following happens, after clipping the brushes become invalid and the map does not compile
![image](https://user-images.githubusercontent.com/98468071/151173713-8548dfa3-da5f-42cd-a9d2-711d7d54ab9a.png)

**Comment by Ulqxiorra** [comment]
Update: This happens if the cylinder has 16 faces

**Comment by ficool2** [comment]
I can't reproduce this, do you have a .vmf of the exact cylinder?

**Comment by Ulqxiorra** [comment]
Checked again, everything works as it should
