### ISSUE TITLE
[Bug, 8857, TF2] Crash When Redoing Displacement Power Changes?

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#88]
was working with some displacements and undoing changes. I'd changed some of them from power 2 to power 3 and accidentally undid that change. I tried redoing that change, aand crash. bizarrely and concerningly, there was no autosave, nor even a crash dump. there was a recent normal autosave, but I dunno if that'd be helpful.

**Comment by ficool2** [comment]
Fixed in next build
