### ISSUE TITLE
[Feature Request] Speed up logic.

### ISSUE THREAD

**Issue by MARK2580** [ficool2/HammerPlusPlus-Issue-Tracker#89]
If possible, speed up the work of the transition to I/O entities. At the moment, on heavy maps like the 1st Ravenholm map, it is almost impossible to work with I/O, because. all this lags very strongly up to the fall of the editor. (same with the standard hammer)

https://user-images.githubusercontent.com/11617079/151225855-d085a47c-d3f8-4bcf-bc02-7f07dd7314d0.mp4

https://user-images.githubusercontent.com/11617079/151225835-6e61be7d-1710-4880-a5ac-35b5c1e9cb70.mp4

.

**Comment by Moltard** [comment]
i decompiled the map (d1 town 01) and it also seems slow when going in output tab. opening entity properties is fine but when switching to output. When there are few outputs on the entity, there is like a tiny delay (probably Hammer is researching all outputs linked to the entity)

[d1_town_01_d.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7965741/d1_town_01_d.zip)

I tried on one of my personal maps, where i got tons and tons of output on single entities and it does the same lag 

So possibly the output system need some kind of rework.

**Comment by ficool2** [comment]
Should be significantly faster next build, Hammer was refreshing the output list 6 times, now it's done only once

**Comment by MARK2580** [comment]
> Should be significantly faster next build, Hammer was refreshing the output list 6 times, now it's done only once

Certainly not perfect, but it really became much faster. Waiting for properties to open always scares me, most often this led to a crash in the original hammer.
