### ISSUE TITLE
[Bug] 3D Viewport turns completely white if Water shader is missing $cubemap

### ISSUE THREAD

**Issue by WereTech** [ficool2/HammerPlusPlus-Issue-Tracker#9]
If the top face of a brush with this Water texture goes below Z = 0, the 3D Viewport will turn entirely white while the texture is within view, but will turn back to normal if not visible or returns to above Z 0.

Above Z 0: https://i.imgur.com/ekt7VXg.png

Below Z 0: https://i.imgur.com/iLMwMYh.png

**Comment by ficool2** [comment]
I'm unsure if this is fixable as it seems to be deeply rooted in shaders, it can be fixed though by adding this parameter to the texture's .vmt
`"$envmap" "env_cubemap"`

**Comment by WereTech** [comment]
> I'm unsure if this is fixable as it seems to be deeply rooted in shaders, it can be fixed though by adding this parameter to the texture's .vmt `"$envmap" "env_cubemap"`

Yeah I get that part, just saying this can cause some bad issues someone could be completely unaware of. Maybe disable it from being rendered entirely in those cases.

**Comment by ficool2** [comment]
I looked into this and there's no easy way to fix this sadly, since it's not that of a common issue I'll close this
