### ISSUE TITLE
[Bug] Reducing displacement power destroys random vertices

### ISSUE THREAD

**Issue by SuperSlimek** [ficool2/HammerPlusPlus-Issue-Tracker#91]
Occasionally reducing displacement power causes individual random vertices to go bonkers (for example disappear or get pushed into infinity). It also caused a crash. Unfortunately I can't reproduce it consistently. 
[mdmp.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7945924/mdmp.zip)

**Comment by ficool2** [comment]
Fixed in next build
