### ISSUE TITLE
[Bug, 8857, TF2] Crash When Undoing Faulty Sews?

### ISSUE THREAD

**Issue by Kestrelguy** [ficool2/HammerPlusPlus-Issue-Tracker#98]
had problems sewing some displacements because apparently more than 2 selected faces shared a single edge? I hit okay and started to click around trying to figure out what I did wrong. I accidentally made a couple changes and started undoing them. I ended up undoing the bad sew as well... cue crash. unlike the last one, there were no changes in displacement power involved, and a crash autosave and crash log were generated.
[faulty sew undo crash.zip](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker/files/7951923/faulty.sew.undo.crash.zip).

**Comment by ficool2** [comment]
Should be fixed in build 8858
